// Code generated by protoc-gen-go.
// source: openrtb.proto
// DO NOT EDIT!

/*
Package openrtb is a generated protocol buffer package.

It is generated from these files:
	openrtb.proto

It has these top-level messages:
	BidRequest
	BidResponse
*/
package openrtb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type BidRequest_DeviceType int32

const (
	BidRequest_DeviceType_Unknown BidRequest_DeviceType = 0
	BidRequest_DeviceType_Pad     BidRequest_DeviceType = 1
	BidRequest_DeviceType_Phone   BidRequest_DeviceType = 2
	BidRequest_DeviceType_PC      BidRequest_DeviceType = 3
	BidRequest_DeviceType_TV      BidRequest_DeviceType = 4
	BidRequest_DeviceType_TVBox   BidRequest_DeviceType = 5
)

var BidRequest_DeviceType_name = map[int32]string{
	0: "DeviceType_Unknown",
	1: "DeviceType_Pad",
	2: "DeviceType_Phone",
	3: "DeviceType_PC",
	4: "DeviceType_TV",
	5: "DeviceType_TVBox",
}
var BidRequest_DeviceType_value = map[string]int32{
	"DeviceType_Unknown": 0,
	"DeviceType_Pad":     1,
	"DeviceType_Phone":   2,
	"DeviceType_PC":      3,
	"DeviceType_TV":      4,
	"DeviceType_TVBox":   5,
}

func (x BidRequest_DeviceType) Enum() *BidRequest_DeviceType {
	p := new(BidRequest_DeviceType)
	*p = x
	return p
}
func (x BidRequest_DeviceType) String() string {
	return proto.EnumName(BidRequest_DeviceType_name, int32(x))
}
func (x *BidRequest_DeviceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_DeviceType_value, data, "BidRequest_DeviceType")
	if err != nil {
		return err
	}
	*x = BidRequest_DeviceType(value)
	return nil
}

type BidRequest_OsType int32

const (
	BidRequest_OsType_Android BidRequest_OsType = 0
	BidRequest_OsType_iOS     BidRequest_OsType = 1
	BidRequest_OsType_WP      BidRequest_OsType = 2
	BidRequest_OsType_Other   BidRequest_OsType = 3
)

var BidRequest_OsType_name = map[int32]string{
	0: "OsType_Android",
	1: "OsType_iOS",
	2: "OsType_WP",
	3: "OsType_Other",
}
var BidRequest_OsType_value = map[string]int32{
	"OsType_Android": 0,
	"OsType_iOS":     1,
	"OsType_WP":      2,
	"OsType_Other":   3,
}

func (x BidRequest_OsType) Enum() *BidRequest_OsType {
	p := new(BidRequest_OsType)
	*p = x
	return p
}
func (x BidRequest_OsType) String() string {
	return proto.EnumName(BidRequest_OsType_name, int32(x))
}
func (x *BidRequest_OsType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_OsType_value, data, "BidRequest_OsType")
	if err != nil {
		return err
	}
	*x = BidRequest_OsType(value)
	return nil
}

type BidRequest_ConnectionType int32

const (
	BidRequest_ConnectionType_Unknown      BidRequest_ConnectionType = 0
	BidRequest_ConnectionType_Wifi         BidRequest_ConnectionType = 1
	BidRequest_ConnectionType_Cell2G       BidRequest_ConnectionType = 2
	BidRequest_ConnectionType_Cell3G       BidRequest_ConnectionType = 3
	BidRequest_ConnectionType_Cell4G       BidRequest_ConnectionType = 4
	BidRequest_ConnectionType_Cell_Unknown BidRequest_ConnectionType = 100
	BidRequest_ConnectionType_Ethernet     BidRequest_ConnectionType = 101
)

var BidRequest_ConnectionType_name = map[int32]string{
	0:   "ConnectionType_Unknown",
	1:   "ConnectionType_Wifi",
	2:   "ConnectionType_Cell2G",
	3:   "ConnectionType_Cell3G",
	4:   "ConnectionType_Cell4G",
	100: "ConnectionType_Cell_Unknown",
	101: "ConnectionType_Ethernet",
}
var BidRequest_ConnectionType_value = map[string]int32{
	"ConnectionType_Unknown":      0,
	"ConnectionType_Wifi":         1,
	"ConnectionType_Cell2G":       2,
	"ConnectionType_Cell3G":       3,
	"ConnectionType_Cell4G":       4,
	"ConnectionType_Cell_Unknown": 100,
	"ConnectionType_Ethernet":     101,
}

func (x BidRequest_ConnectionType) Enum() *BidRequest_ConnectionType {
	p := new(BidRequest_ConnectionType)
	*p = x
	return p
}
func (x BidRequest_ConnectionType) String() string {
	return proto.EnumName(BidRequest_ConnectionType_name, int32(x))
}
func (x *BidRequest_ConnectionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_ConnectionType_value, data, "BidRequest_ConnectionType")
	if err != nil {
		return err
	}
	*x = BidRequest_ConnectionType(value)
	return nil
}

type BidRequest_Gender int32

const (
	BidRequest_Gender_Unkown BidRequest_Gender = 0
	BidRequest_Gender_Male   BidRequest_Gender = 1
	BidRequest_Gender_Female BidRequest_Gender = 2
	BidRequest_Gender_Other  BidRequest_Gender = 3
)

var BidRequest_Gender_name = map[int32]string{
	0: "Gender_Unkown",
	1: "Gender_Male",
	2: "Gender_Female",
	3: "Gender_Other",
}
var BidRequest_Gender_value = map[string]int32{
	"Gender_Unkown": 0,
	"Gender_Male":   1,
	"Gender_Female": 2,
	"Gender_Other":  3,
}

func (x BidRequest_Gender) Enum() *BidRequest_Gender {
	p := new(BidRequest_Gender)
	*p = x
	return p
}
func (x BidRequest_Gender) String() string {
	return proto.EnumName(BidRequest_Gender_name, int32(x))
}
func (x *BidRequest_Gender) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_Gender_value, data, "BidRequest_Gender")
	if err != nil {
		return err
	}
	*x = BidRequest_Gender(value)
	return nil
}

type BidRequest_SlotType int32

const (
	BidRequest_SlotType_Feeds          BidRequest_SlotType = 1
	BidRequest_SlotType_Banner         BidRequest_SlotType = 2
	BidRequest_SlotType_Interstitial   BidRequest_SlotType = 3
	BidRequest_SlotType_Native         BidRequest_SlotType = 5
	BidRequest_SlotType_Card           BidRequest_SlotType = 6
	BidRequest_SlotType_Splash         BidRequest_SlotType = 7
	BidRequest_SlotType_TCVideo        BidRequest_SlotType = 8
	BidRequest_SlotType_PicAndVideo    BidRequest_SlotType = 9
	BidRequest_SlotType_PicAndNative   BidRequest_SlotType = 10
	BidRequest_SlotType_VideoAndNative BidRequest_SlotType = 11
	BidRequest_SlotType_All            BidRequest_SlotType = 12
	BidRequest_SlotType_Dynamic        BidRequest_SlotType = 13
	BidRequest_SlotType_FullScreen     BidRequest_SlotType = 14
	BidRequest_SlotType_VideoPause     BidRequest_SlotType = 15
)

var BidRequest_SlotType_name = map[int32]string{
	1:  "SlotType_Feeds",
	2:  "SlotType_Banner",
	3:  "SlotType_Interstitial",
	5:  "SlotType_Native",
	6:  "SlotType_Card",
	7:  "SlotType_Splash",
	8:  "SlotType_TCVideo",
	9:  "SlotType_PicAndVideo",
	10: "SlotType_PicAndNative",
	11: "SlotType_VideoAndNative",
	12: "SlotType_All",
	13: "SlotType_Dynamic",
	14: "SlotType_FullScreen",
	15: "SlotType_VideoPause",
}
var BidRequest_SlotType_value = map[string]int32{
	"SlotType_Feeds":          1,
	"SlotType_Banner":         2,
	"SlotType_Interstitial":   3,
	"SlotType_Native":         5,
	"SlotType_Card":           6,
	"SlotType_Splash":         7,
	"SlotType_TCVideo":        8,
	"SlotType_PicAndVideo":    9,
	"SlotType_PicAndNative":   10,
	"SlotType_VideoAndNative": 11,
	"SlotType_All":            12,
	"SlotType_Dynamic":        13,
	"SlotType_FullScreen":     14,
	"SlotType_VideoPause":     15,
}

func (x BidRequest_SlotType) Enum() *BidRequest_SlotType {
	p := new(BidRequest_SlotType)
	*p = x
	return p
}
func (x BidRequest_SlotType) String() string {
	return proto.EnumName(BidRequest_SlotType_name, int32(x))
}
func (x *BidRequest_SlotType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_SlotType_value, data, "BidRequest_SlotType")
	if err != nil {
		return err
	}
	*x = BidRequest_SlotType(value)
	return nil
}

type BidRequest_EncType int32

const (
	BidRequest_EncType_Origin BidRequest_EncType = 0
	BidRequest_EncType_Md5    BidRequest_EncType = 1
	BidRequest_EncType_Sha1   BidRequest_EncType = 2
)

var BidRequest_EncType_name = map[int32]string{
	0: "EncType_Origin",
	1: "EncType_Md5",
	2: "EncType_Sha1",
}
var BidRequest_EncType_value = map[string]int32{
	"EncType_Origin": 0,
	"EncType_Md5":    1,
	"EncType_Sha1":   2,
}

func (x BidRequest_EncType) Enum() *BidRequest_EncType {
	p := new(BidRequest_EncType)
	*p = x
	return p
}
func (x BidRequest_EncType) String() string {
	return proto.EnumName(BidRequest_EncType_name, int32(x))
}
func (x *BidRequest_EncType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_EncType_value, data, "BidRequest_EncType")
	if err != nil {
		return err
	}
	*x = BidRequest_EncType(value)
	return nil
}

type BidRequest_SaleMode int32

const (
	BidRequest_SaleModeRTB BidRequest_SaleMode = 0
	BidRequest_SaleModePA  BidRequest_SaleMode = 1
	BidRequest_SaleModePD  BidRequest_SaleMode = 2
	BidRequest_SaleModePDB BidRequest_SaleMode = 3
)

var BidRequest_SaleMode_name = map[int32]string{
	0: "SaleModeRTB",
	1: "SaleModePA",
	2: "SaleModePD",
	3: "SaleModePDB",
}
var BidRequest_SaleMode_value = map[string]int32{
	"SaleModeRTB": 0,
	"SaleModePA":  1,
	"SaleModePD":  2,
	"SaleModePDB": 3,
}

func (x BidRequest_SaleMode) Enum() *BidRequest_SaleMode {
	p := new(BidRequest_SaleMode)
	*p = x
	return p
}
func (x BidRequest_SaleMode) String() string {
	return proto.EnumName(BidRequest_SaleMode_name, int32(x))
}
func (x *BidRequest_SaleMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_SaleMode_value, data, "BidRequest_SaleMode")
	if err != nil {
		return err
	}
	*x = BidRequest_SaleMode(value)
	return nil
}

type BidRequest_ImageType int32

const (
	BidRequest_ImageType_Icon      BidRequest_ImageType = 1
	BidRequest_ImageType_Logo      BidRequest_ImageType = 2
	BidRequest_ImageType_Main      BidRequest_ImageType = 3
	BidRequest_ImageType_WithVideo BidRequest_ImageType = 4
)

var BidRequest_ImageType_name = map[int32]string{
	1: "ImageType_Icon",
	2: "ImageType_Logo",
	3: "ImageType_Main",
	4: "ImageType_WithVideo",
}
var BidRequest_ImageType_value = map[string]int32{
	"ImageType_Icon":      1,
	"ImageType_Logo":      2,
	"ImageType_Main":      3,
	"ImageType_WithVideo": 4,
}

func (x BidRequest_ImageType) Enum() *BidRequest_ImageType {
	p := new(BidRequest_ImageType)
	*p = x
	return p
}
func (x BidRequest_ImageType) String() string {
	return proto.EnumName(BidRequest_ImageType_name, int32(x))
}
func (x *BidRequest_ImageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_ImageType_value, data, "BidRequest_ImageType")
	if err != nil {
		return err
	}
	*x = BidRequest_ImageType(value)
	return nil
}

type BidRequest_ContextType int32

const (
	BidRequest_ContextType_Unkown BidRequest_ContextType = 0
	BidRequest_ContextType_Video  BidRequest_ContextType = 1
	BidRequest_ContextType_Game   BidRequest_ContextType = 2
	BidRequest_ContextType_Music  BidRequest_ContextType = 3
	BidRequest_ContextType_App    BidRequest_ContextType = 4
	BidRequest_ContextType_Text   BidRequest_ContextType = 5
)

var BidRequest_ContextType_name = map[int32]string{
	0: "ContextType_Unkown",
	1: "ContextType_Video",
	2: "ContextType_Game",
	3: "ContextType_Music",
	4: "ContextType_App",
	5: "ContextType_Text",
}
var BidRequest_ContextType_value = map[string]int32{
	"ContextType_Unkown": 0,
	"ContextType_Video":  1,
	"ContextType_Game":   2,
	"ContextType_Music":  3,
	"ContextType_App":    4,
	"ContextType_Text":   5,
}

func (x BidRequest_ContextType) Enum() *BidRequest_ContextType {
	p := new(BidRequest_ContextType)
	*p = x
	return p
}
func (x BidRequest_ContextType) String() string {
	return proto.EnumName(BidRequest_ContextType_name, int32(x))
}
func (x *BidRequest_ContextType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_ContextType_value, data, "BidRequest_ContextType")
	if err != nil {
		return err
	}
	*x = BidRequest_ContextType(value)
	return nil
}

type BidRequest_Video_VideoLinearity int32

const (
	BidRequest_Video_VideoLinearity_Instream BidRequest_Video_VideoLinearity = 1
	BidRequest_Video_VideoLinearity_Overlay  BidRequest_Video_VideoLinearity = 2
)

var BidRequest_Video_VideoLinearity_name = map[int32]string{
	1: "VideoLinearity_Instream",
	2: "VideoLinearity_Overlay",
}
var BidRequest_Video_VideoLinearity_value = map[string]int32{
	"VideoLinearity_Instream": 1,
	"VideoLinearity_Overlay":  2,
}

func (x BidRequest_Video_VideoLinearity) Enum() *BidRequest_Video_VideoLinearity {
	p := new(BidRequest_Video_VideoLinearity)
	*p = x
	return p
}
func (x BidRequest_Video_VideoLinearity) String() string {
	return proto.EnumName(BidRequest_Video_VideoLinearity_name, int32(x))
}
func (x *BidRequest_Video_VideoLinearity) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_Video_VideoLinearity_value, data, "BidRequest_Video_VideoLinearity")
	if err != nil {
		return err
	}
	*x = BidRequest_Video_VideoLinearity(value)
	return nil
}

type BidRequest_Video_PlaybackMethod int32

const (
	BidRequest_Video_PlaybackMethod_AutoPlay     BidRequest_Video_PlaybackMethod = 1
	BidRequest_Video_PlaybackMethod_AutoPlayMute BidRequest_Video_PlaybackMethod = 2
	BidRequest_Video_PlaybackMethod_ClickPlay    BidRequest_Video_PlaybackMethod = 3
	BidRequest_Video_PlaybackMethod_MouseOver    BidRequest_Video_PlaybackMethod = 4
)

var BidRequest_Video_PlaybackMethod_name = map[int32]string{
	1: "PlaybackMethod_AutoPlay",
	2: "PlaybackMethod_AutoPlayMute",
	3: "PlaybackMethod_ClickPlay",
	4: "PlaybackMethod_MouseOver",
}
var BidRequest_Video_PlaybackMethod_value = map[string]int32{
	"PlaybackMethod_AutoPlay":     1,
	"PlaybackMethod_AutoPlayMute": 2,
	"PlaybackMethod_ClickPlay":    3,
	"PlaybackMethod_MouseOver":    4,
}

func (x BidRequest_Video_PlaybackMethod) Enum() *BidRequest_Video_PlaybackMethod {
	p := new(BidRequest_Video_PlaybackMethod)
	*p = x
	return p
}
func (x BidRequest_Video_PlaybackMethod) String() string {
	return proto.EnumName(BidRequest_Video_PlaybackMethod_name, int32(x))
}
func (x *BidRequest_Video_PlaybackMethod) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_Video_PlaybackMethod_value, data, "BidRequest_Video_PlaybackMethod")
	if err != nil {
		return err
	}
	*x = BidRequest_Video_PlaybackMethod(value)
	return nil
}

type BidResponse_EventName int32

const (
	BidResponse_VideoTrack_FirstQuartile BidResponse_EventName = 1
	BidResponse_VideoTrack_MidPoint      BidResponse_EventName = 2
	BidResponse_VideoTrack_ThirdQuartile BidResponse_EventName = 3
	BidResponse_VideoTrack_Complete      BidResponse_EventName = 4
)

var BidResponse_EventName_name = map[int32]string{
	1: "VideoTrack_FirstQuartile",
	2: "VideoTrack_MidPoint",
	3: "VideoTrack_ThirdQuartile",
	4: "VideoTrack_Complete",
}
var BidResponse_EventName_value = map[string]int32{
	"VideoTrack_FirstQuartile": 1,
	"VideoTrack_MidPoint":      2,
	"VideoTrack_ThirdQuartile": 3,
	"VideoTrack_Complete":      4,
}

func (x BidResponse_EventName) Enum() *BidResponse_EventName {
	p := new(BidResponse_EventName)
	*p = x
	return p
}
func (x BidResponse_EventName) String() string {
	return proto.EnumName(BidResponse_EventName_name, int32(x))
}
func (x *BidResponse_EventName) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidResponse_EventName_value, data, "BidResponse_EventName")
	if err != nil {
		return err
	}
	*x = BidResponse_EventName(value)
	return nil
}

type BidResponse_Attr int32

const (
	BidResponse_Attr_Web      BidResponse_Attr = 20
	BidResponse_Attr_Download BidResponse_Attr = 22
)

var BidResponse_Attr_name = map[int32]string{
	20: "Attr_Web",
	22: "Attr_Download",
}
var BidResponse_Attr_value = map[string]int32{
	"Attr_Web":      20,
	"Attr_Download": 22,
}

func (x BidResponse_Attr) Enum() *BidResponse_Attr {
	p := new(BidResponse_Attr)
	*p = x
	return p
}
func (x BidResponse_Attr) String() string {
	return proto.EnumName(BidResponse_Attr_name, int32(x))
}
func (x *BidResponse_Attr) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidResponse_Attr_value, data, "BidResponse_Attr")
	if err != nil {
		return err
	}
	*x = BidResponse_Attr(value)
	return nil
}

type BidRequest struct {
	// Zyz生产唯一竞价ID
	Bid    *string                  `protobuf:"bytes,1,opt,name=bid" json:"bid,omitempty"`
	IsTest *bool                    `protobuf:"varint,20,opt,name=is_test,def=0" json:"is_test,omitempty"`
	IsPing *bool                    `protobuf:"varint,21,opt,name=is_ping,def=0" json:"is_ping,omitempty"`
	Sid    *string                  `protobuf:"bytes,22,opt,name=sid" json:"sid,omitempty"`
	Imps   []*BidRequest_Impression `protobuf:"bytes,2,rep,name=imps" json:"imps,omitempty"`
	App    *BidRequest_App          `protobuf:"bytes,3,opt,name=app" json:"app,omitempty"`
	Device *BidRequest_Device       `protobuf:"bytes,4,opt,name=device" json:"device,omitempty"`
	User   *BidRequest_User         `protobuf:"bytes,5,opt,name=user" json:"user,omitempty"`
	// 禁止的行业类别
	Bcat []string `protobuf:"bytes,6,rep,name=bcat" json:"bcat,omitempty"`
	// 广告主黑名单
	Badv []string         `protobuf:"bytes,7,rep,name=badv" json:"badv,omitempty"`
	Bapp []string         `protobuf:"bytes,8,rep,name=bapp" json:"bapp,omitempty"`
	Site *BidRequest_Site `protobuf:"bytes,9,opt,name=site" json:"site,omitempty"`
	// Auction type, where 1 = First Price, 2 = Second Price Plus.
	At *int32 `protobuf:"varint,10,opt,name=At,def=2" json:"At,omitempty"`
	// Maximum time in milliseconds the exchange allows for bids
	// to be received including Internet latency to avoid timeout.
	Tmax             *int32   `protobuf:"varint,11,opt,name=Tmax" json:"Tmax,omitempty"`
	Wseat            []string `protobuf:"bytes,12,rep,name=wseat" json:"wseat,omitempty"`
	Bseat            []string `protobuf:"bytes,13,rep,name=bseat" json:"bseat,omitempty"`
	SupportDeeplink  *bool    `protobuf:"varint,14,opt,name=supportDeeplink" json:"supportDeeplink,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BidRequest) Reset()         { *m = BidRequest{} }
func (m *BidRequest) String() string { return proto.CompactTextString(m) }
func (*BidRequest) ProtoMessage()    {}

const Default_BidRequest_IsTest bool = false
const Default_BidRequest_IsPing bool = false
const Default_BidRequest_At int32 = 2

func (m *BidRequest) GetBid() string {
	if m != nil && m.Bid != nil {
		return *m.Bid
	}
	return ""
}

func (m *BidRequest) GetIsTest() bool {
	if m != nil && m.IsTest != nil {
		return *m.IsTest
	}
	return Default_BidRequest_IsTest
}

func (m *BidRequest) GetIsPing() bool {
	if m != nil && m.IsPing != nil {
		return *m.IsPing
	}
	return Default_BidRequest_IsPing
}

func (m *BidRequest) GetSid() string {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return ""
}

func (m *BidRequest) GetImps() []*BidRequest_Impression {
	if m != nil {
		return m.Imps
	}
	return nil
}

func (m *BidRequest) GetApp() *BidRequest_App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *BidRequest) GetDevice() *BidRequest_Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *BidRequest) GetUser() *BidRequest_User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *BidRequest) GetBcat() []string {
	if m != nil {
		return m.Bcat
	}
	return nil
}

func (m *BidRequest) GetBadv() []string {
	if m != nil {
		return m.Badv
	}
	return nil
}

func (m *BidRequest) GetBapp() []string {
	if m != nil {
		return m.Bapp
	}
	return nil
}

func (m *BidRequest) GetSite() *BidRequest_Site {
	if m != nil {
		return m.Site
	}
	return nil
}

func (m *BidRequest) GetAt() int32 {
	if m != nil && m.At != nil {
		return *m.At
	}
	return Default_BidRequest_At
}

func (m *BidRequest) GetTmax() int32 {
	if m != nil && m.Tmax != nil {
		return *m.Tmax
	}
	return 0
}

func (m *BidRequest) GetWseat() []string {
	if m != nil {
		return m.Wseat
	}
	return nil
}

func (m *BidRequest) GetBseat() []string {
	if m != nil {
		return m.Bseat
	}
	return nil
}

func (m *BidRequest) GetSupportDeeplink() bool {
	if m != nil && m.SupportDeeplink != nil {
		return *m.SupportDeeplink
	}
	return false
}

type BidRequest_Size struct {
	W                *int32 `protobuf:"varint,1,req,name=w" json:"w,omitempty"`
	H                *int32 `protobuf:"varint,2,req,name=h" json:"h,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BidRequest_Size) Reset()         { *m = BidRequest_Size{} }
func (m *BidRequest_Size) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Size) ProtoMessage()    {}

func (m *BidRequest_Size) GetW() int32 {
	if m != nil && m.W != nil {
		return *m.W
	}
	return 0
}

func (m *BidRequest_Size) GetH() int32 {
	if m != nil && m.H != nil {
		return *m.H
	}
	return 0
}

type BidRequest_Format struct {
	W                *int32 `protobuf:"varint,1,opt,name=w" json:"w,omitempty"`
	H                *int32 `protobuf:"varint,2,opt,name=h" json:"h,omitempty"`
	Wratio           *int32 `protobuf:"varint,3,opt,name=wratio" json:"wratio,omitempty"`
	Hratio           *int32 `protobuf:"varint,4,opt,name=hratio" json:"hratio,omitempty"`
	Wmin             *int32 `protobuf:"varint,5,opt,name=wmin" json:"wmin,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BidRequest_Format) Reset()         { *m = BidRequest_Format{} }
func (m *BidRequest_Format) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Format) ProtoMessage()    {}

func (m *BidRequest_Format) GetW() int32 {
	if m != nil && m.W != nil {
		return *m.W
	}
	return 0
}

func (m *BidRequest_Format) GetH() int32 {
	if m != nil && m.H != nil {
		return *m.H
	}
	return 0
}

func (m *BidRequest_Format) GetWratio() int32 {
	if m != nil && m.Wratio != nil {
		return *m.Wratio
	}
	return 0
}

func (m *BidRequest_Format) GetHratio() int32 {
	if m != nil && m.Hratio != nil {
		return *m.Hratio
	}
	return 0
}

func (m *BidRequest_Format) GetWmin() int32 {
	if m != nil && m.Wmin != nil {
		return *m.Wmin
	}
	return 0
}

// banner
type BidRequest_Banner struct {
	// 广告位的尺寸
	SlotSize *BidRequest_Size `protobuf:"bytes,1,opt,name=slot_size" json:"slot_size,omitempty"`
	// 允许的素材尺寸，如果format为空，取slot_size
	Format []*BidRequest_Format `protobuf:"bytes,2,rep,name=format" json:"format,omitempty"`
	// 允许的素材类型(RFC2046)
	Mimes            []string `protobuf:"bytes,4,rep,name=mimes" json:"mimes,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BidRequest_Banner) Reset()         { *m = BidRequest_Banner{} }
func (m *BidRequest_Banner) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Banner) ProtoMessage()    {}

func (m *BidRequest_Banner) GetSlotSize() *BidRequest_Size {
	if m != nil {
		return m.SlotSize
	}
	return nil
}

func (m *BidRequest_Banner) GetFormat() []*BidRequest_Format {
	if m != nil {
		return m.Format
	}
	return nil
}

func (m *BidRequest_Banner) GetMimes() []string {
	if m != nil {
		return m.Mimes
	}
	return nil
}

type BidRequest_ImageAsset struct {
	Type             *BidRequest_ImageType `protobuf:"varint,1,opt,name=type,enum=openrtb.BidRequest_ImageType" json:"type,omitempty"`
	W                *int32                `protobuf:"varint,2,opt,name=w" json:"w,omitempty"`
	Wmin             *int32                `protobuf:"varint,3,opt,name=wmin" json:"wmin,omitempty"`
	H                *int32                `protobuf:"varint,4,opt,name=h" json:"h,omitempty"`
	Hmin             *int32                `protobuf:"varint,5,opt,name=hmin" json:"hmin,omitempty"`
	Mimes            []string              `protobuf:"bytes,6,rep,name=mimes" json:"mimes,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *BidRequest_ImageAsset) Reset()         { *m = BidRequest_ImageAsset{} }
func (m *BidRequest_ImageAsset) String() string { return proto.CompactTextString(m) }
func (*BidRequest_ImageAsset) ProtoMessage()    {}

func (m *BidRequest_ImageAsset) GetType() BidRequest_ImageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return BidRequest_ImageType_Icon
}

func (m *BidRequest_ImageAsset) GetW() int32 {
	if m != nil && m.W != nil {
		return *m.W
	}
	return 0
}

func (m *BidRequest_ImageAsset) GetWmin() int32 {
	if m != nil && m.Wmin != nil {
		return *m.Wmin
	}
	return 0
}

func (m *BidRequest_ImageAsset) GetH() int32 {
	if m != nil && m.H != nil {
		return *m.H
	}
	return 0
}

func (m *BidRequest_ImageAsset) GetHmin() int32 {
	if m != nil && m.Hmin != nil {
		return *m.Hmin
	}
	return 0
}

func (m *BidRequest_ImageAsset) GetMimes() []string {
	if m != nil {
		return m.Mimes
	}
	return nil
}

type BidRequest_VideoAsset struct {
	Minduration      *int32   `protobuf:"varint,1,opt,name=minduration" json:"minduration,omitempty"`
	Maxduration      *int32   `protobuf:"varint,2,opt,name=maxduration" json:"maxduration,omitempty"`
	Mimes            []string `protobuf:"bytes,3,rep,name=mimes" json:"mimes,omitempty"`
	W                *int32   `protobuf:"varint,4,opt,name=w" json:"w,omitempty"`
	H                *int32   `protobuf:"varint,5,opt,name=h" json:"h,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BidRequest_VideoAsset) Reset()         { *m = BidRequest_VideoAsset{} }
func (m *BidRequest_VideoAsset) String() string { return proto.CompactTextString(m) }
func (*BidRequest_VideoAsset) ProtoMessage()    {}

func (m *BidRequest_VideoAsset) GetMinduration() int32 {
	if m != nil && m.Minduration != nil {
		return *m.Minduration
	}
	return 0
}

func (m *BidRequest_VideoAsset) GetMaxduration() int32 {
	if m != nil && m.Maxduration != nil {
		return *m.Maxduration
	}
	return 0
}

func (m *BidRequest_VideoAsset) GetMimes() []string {
	if m != nil {
		return m.Mimes
	}
	return nil
}

func (m *BidRequest_VideoAsset) GetW() int32 {
	if m != nil && m.W != nil {
		return *m.W
	}
	return 0
}

func (m *BidRequest_VideoAsset) GetH() int32 {
	if m != nil && m.H != nil {
		return *m.H
	}
	return 0
}

type BidRequest_Asset struct {
	Id               *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	TitleLen         *int32                 `protobuf:"varint,2,opt,name=title_len,def=30" json:"title_len,omitempty"`
	Image            *BidRequest_ImageAsset `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
	Video            *BidRequest_VideoAsset `protobuf:"bytes,4,opt,name=video" json:"video,omitempty"`
	IsRequired       *int32                 `protobuf:"varint,5,opt,name=isRequired" json:"isRequired,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *BidRequest_Asset) Reset()         { *m = BidRequest_Asset{} }
func (m *BidRequest_Asset) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Asset) ProtoMessage()    {}

const Default_BidRequest_Asset_TitleLen int32 = 30

func (m *BidRequest_Asset) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *BidRequest_Asset) GetTitleLen() int32 {
	if m != nil && m.TitleLen != nil {
		return *m.TitleLen
	}
	return Default_BidRequest_Asset_TitleLen
}

func (m *BidRequest_Asset) GetImage() *BidRequest_ImageAsset {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *BidRequest_Asset) GetVideo() *BidRequest_VideoAsset {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *BidRequest_Asset) GetIsRequired() int32 {
	if m != nil && m.IsRequired != nil {
		return *m.IsRequired
	}
	return 0
}

// native
type BidRequest_Native struct {
	// feeds的上下文类型，参考接入文档定义
	ContextType      *int32              `protobuf:"varint,1,opt,name=context_type" json:"context_type,omitempty"`
	ContextSutype    *int32              `protobuf:"varint,2,opt,name=context_sutype" json:"context_sutype,omitempty"`
	Asset            []*BidRequest_Asset `protobuf:"bytes,3,rep,name=asset" json:"asset,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *BidRequest_Native) Reset()         { *m = BidRequest_Native{} }
func (m *BidRequest_Native) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Native) ProtoMessage()    {}

func (m *BidRequest_Native) GetContextType() int32 {
	if m != nil && m.ContextType != nil {
		return *m.ContextType
	}
	return 0
}

func (m *BidRequest_Native) GetContextSutype() int32 {
	if m != nil && m.ContextSutype != nil {
		return *m.ContextSutype
	}
	return 0
}

func (m *BidRequest_Native) GetAsset() []*BidRequest_Asset {
	if m != nil {
		return m.Asset
	}
	return nil
}

// video
type BidRequest_Video struct {
	SlotSize         *BidRequest_Size                 `protobuf:"bytes,1,opt,name=slot_size" json:"slot_size,omitempty"`
	Mimes            []string                         `protobuf:"bytes,2,rep,name=mimes" json:"mimes,omitempty"`
	Minduration      *int32                           `protobuf:"varint,3,opt,name=minduration" json:"minduration,omitempty"`
	Maxduration      *int32                           `protobuf:"varint,4,opt,name=maxduration" json:"maxduration,omitempty"`
	Minbitrate       *int32                           `protobuf:"varint,5,opt,name=minbitrate" json:"minbitrate,omitempty"`
	Maxbitrate       *int32                           `protobuf:"varint,6,opt,name=maxbitrate" json:"maxbitrate,omitempty"`
	Skipable         *bool                            `protobuf:"varint,7,opt,name=skipable" json:"skipable,omitempty"`
	Skipafter        *int32                           `protobuf:"varint,8,opt,name=skipafter" json:"skipafter,omitempty"`
	Linearity        *BidRequest_Video_VideoLinearity `protobuf:"varint,9,opt,name=linearity,enum=openrtb.BidRequest_Video_VideoLinearity" json:"linearity,omitempty"`
	Boxingallowed    *bool                            `protobuf:"varint,10,opt,name=boxingallowed" json:"boxingallowed,omitempty"`
	PlaybackMethod   *BidRequest_Video_PlaybackMethod `protobuf:"varint,11,opt,name=playback_method,enum=openrtb.BidRequest_Video_PlaybackMethod" json:"playback_method,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *BidRequest_Video) Reset()         { *m = BidRequest_Video{} }
func (m *BidRequest_Video) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Video) ProtoMessage()    {}

func (m *BidRequest_Video) GetSlotSize() *BidRequest_Size {
	if m != nil {
		return m.SlotSize
	}
	return nil
}

func (m *BidRequest_Video) GetMimes() []string {
	if m != nil {
		return m.Mimes
	}
	return nil
}

func (m *BidRequest_Video) GetMinduration() int32 {
	if m != nil && m.Minduration != nil {
		return *m.Minduration
	}
	return 0
}

func (m *BidRequest_Video) GetMaxduration() int32 {
	if m != nil && m.Maxduration != nil {
		return *m.Maxduration
	}
	return 0
}

func (m *BidRequest_Video) GetMinbitrate() int32 {
	if m != nil && m.Minbitrate != nil {
		return *m.Minbitrate
	}
	return 0
}

func (m *BidRequest_Video) GetMaxbitrate() int32 {
	if m != nil && m.Maxbitrate != nil {
		return *m.Maxbitrate
	}
	return 0
}

func (m *BidRequest_Video) GetSkipable() bool {
	if m != nil && m.Skipable != nil {
		return *m.Skipable
	}
	return false
}

func (m *BidRequest_Video) GetSkipafter() int32 {
	if m != nil && m.Skipafter != nil {
		return *m.Skipafter
	}
	return 0
}

func (m *BidRequest_Video) GetLinearity() BidRequest_Video_VideoLinearity {
	if m != nil && m.Linearity != nil {
		return *m.Linearity
	}
	return BidRequest_Video_VideoLinearity_Instream
}

func (m *BidRequest_Video) GetBoxingallowed() bool {
	if m != nil && m.Boxingallowed != nil {
		return *m.Boxingallowed
	}
	return false
}

func (m *BidRequest_Video) GetPlaybackMethod() BidRequest_Video_PlaybackMethod {
	if m != nil && m.PlaybackMethod != nil {
		return *m.PlaybackMethod
	}
	return BidRequest_Video_PlaybackMethod_AutoPlay
}

type BidRequest_Metric struct {
	Type *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	// in the range 0.0 ~ 1.0
	Value            *float32 `protobuf:"fixed32,2,opt,name=value" json:"value,omitempty"`
	Vendor           *string  `protobuf:"bytes,3,opt,name=vendor" json:"vendor,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BidRequest_Metric) Reset()         { *m = BidRequest_Metric{} }
func (m *BidRequest_Metric) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Metric) ProtoMessage()    {}

func (m *BidRequest_Metric) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *BidRequest_Metric) GetValue() float32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *BidRequest_Metric) GetVendor() string {
	if m != nil && m.Vendor != nil {
		return *m.Vendor
	}
	return ""
}

// impression对象
type BidRequest_Impression struct {
	// 唯一id
	Id *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// 广告位id
	SlotId *string `protobuf:"bytes,2,opt,name=slotId" json:"slotId,omitempty"`
	// banner对象
	Banner *BidRequest_Banner `protobuf:"bytes,3,opt,name=banner" json:"banner,omitempty"`
	// native对象
	Native *BidRequest_Native `protobuf:"bytes,4,opt,name=native" json:"native,omitempty"`
	// video对象
	Video *BidRequest_Video `protobuf:"bytes,5,opt,name=video" json:"video,omitempty"`
	// 曝光底价  单位: 分/cpm
	Bidfloor *int32 `protobuf:"varint,7,opt,name=bidfloor" json:"bidfloor,omitempty"`
	// preload>0表示请求preload个创意用于缓存, preload=0表示普通竞价
	Preload        *int32               `protobuf:"varint,8,opt,name=preload" json:"preload,omitempty"`
	SlotType       *BidRequest_SlotType `protobuf:"varint,9,opt,name=slot_type,enum=openrtb.BidRequest_SlotType" json:"slot_type,omitempty"`
	Dealid         []string             `protobuf:"bytes,10,rep,name=dealid" json:"dealid,omitempty"`
	SaleMode       *BidRequest_SaleMode `protobuf:"varint,11,opt,name=saleMode,enum=openrtb.BidRequest_SaleMode" json:"saleMode,omitempty"`
	TemplateIdlist []string             `protobuf:"bytes,12,rep,name=templateIdlist" json:"templateIdlist,omitempty"`
	// 预加载广告实际曝光时间，unix时间戳
	PreloadDate *int64 `protobuf:"varint,13,opt,name=preloadDate" json:"preloadDate,omitempty"`
	IsSupportJs *bool  `protobuf:"varint,14,opt,name=isSupportJs" json:"isSupportJs,omitempty"`
	// Name of ad mediation partner, SDK technology, or player responsible for
	// rendering ad (typically video or mobile).
	// Used by some ad servers to customize ad code by partner.
	// Recommended for video and/or apps.
	Displaymanager *string `protobuf:"bytes,15,opt,name=displaymanager" json:"displaymanager,omitempty"`
	// version of displaymanager
	Displaymanagerver *string `protobuf:"bytes,16,opt,name=displaymanagerver" json:"displaymanagerver,omitempty"`
	// Flag to indicate if the impression requires secure HTTPS URL creative assets and markup,
	// where 0 = non-secure, 1 = secure.
	Secure *int32 `protobuf:"varint,17,opt,name=secure" json:"secure,omitempty"`
	// average recent viewability, click-through rate, etc
	Metric []*BidRequest_Metric `protobuf:"bytes,18,rep,name=metric" json:"metric,omitempty"`
	// 动态素材
	IsSupportDynamic *bool  `protobuf:"varint,19,opt,name=isSupportDynamic" json:"isSupportDynamic,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BidRequest_Impression) Reset()         { *m = BidRequest_Impression{} }
func (m *BidRequest_Impression) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Impression) ProtoMessage()    {}

func (m *BidRequest_Impression) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *BidRequest_Impression) GetSlotId() string {
	if m != nil && m.SlotId != nil {
		return *m.SlotId
	}
	return ""
}

func (m *BidRequest_Impression) GetBanner() *BidRequest_Banner {
	if m != nil {
		return m.Banner
	}
	return nil
}

func (m *BidRequest_Impression) GetNative() *BidRequest_Native {
	if m != nil {
		return m.Native
	}
	return nil
}

func (m *BidRequest_Impression) GetVideo() *BidRequest_Video {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *BidRequest_Impression) GetBidfloor() int32 {
	if m != nil && m.Bidfloor != nil {
		return *m.Bidfloor
	}
	return 0
}

func (m *BidRequest_Impression) GetPreload() int32 {
	if m != nil && m.Preload != nil {
		return *m.Preload
	}
	return 0
}

func (m *BidRequest_Impression) GetSlotType() BidRequest_SlotType {
	if m != nil && m.SlotType != nil {
		return *m.SlotType
	}
	return BidRequest_SlotType_Feeds
}

func (m *BidRequest_Impression) GetDealid() []string {
	if m != nil {
		return m.Dealid
	}
	return nil
}

func (m *BidRequest_Impression) GetSaleMode() BidRequest_SaleMode {
	if m != nil && m.SaleMode != nil {
		return *m.SaleMode
	}
	return BidRequest_SaleModeRTB
}

func (m *BidRequest_Impression) GetTemplateIdlist() []string {
	if m != nil {
		return m.TemplateIdlist
	}
	return nil
}

func (m *BidRequest_Impression) GetPreloadDate() int64 {
	if m != nil && m.PreloadDate != nil {
		return *m.PreloadDate
	}
	return 0
}

func (m *BidRequest_Impression) GetIsSupportJs() bool {
	if m != nil && m.IsSupportJs != nil {
		return *m.IsSupportJs
	}
	return false
}

func (m *BidRequest_Impression) GetDisplaymanager() string {
	if m != nil && m.Displaymanager != nil {
		return *m.Displaymanager
	}
	return ""
}

func (m *BidRequest_Impression) GetDisplaymanagerver() string {
	if m != nil && m.Displaymanagerver != nil {
		return *m.Displaymanagerver
	}
	return ""
}

func (m *BidRequest_Impression) GetSecure() int32 {
	if m != nil && m.Secure != nil {
		return *m.Secure
	}
	return 0
}

func (m *BidRequest_Impression) GetMetric() []*BidRequest_Metric {
	if m != nil {
		return m.Metric
	}
	return nil
}

func (m *BidRequest_Impression) GetIsSupportDynamic() bool {
	if m != nil && m.IsSupportDynamic != nil {
		return *m.IsSupportDynamic
	}
	return false
}

type BidRequest_Content struct {
	Title            *string                 `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Url              *string                 `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Keywords         []string                `protobuf:"bytes,3,rep,name=keywords" json:"keywords,omitempty"`
	Artist           *string                 `protobuf:"bytes,4,opt,name=artist" json:"artist,omitempty"`
	Album            *string                 `protobuf:"bytes,5,opt,name=album" json:"album,omitempty"`
	Cat              []string                `protobuf:"bytes,6,rep,name=cat" json:"cat,omitempty"`
	Context          *BidRequest_ContextType `protobuf:"varint,7,opt,name=context,enum=openrtb.BidRequest_ContextType" json:"context,omitempty"`
	Avlen            *int32                  `protobuf:"varint,8,opt,name=avlen" json:"avlen,omitempty"`
	FirstChannel     []string                `protobuf:"bytes,9,rep,name=first_channel" json:"first_channel,omitempty"`
	SecondChannel    []string                `protobuf:"bytes,10,rep,name=second_channel" json:"second_channel,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *BidRequest_Content) Reset()         { *m = BidRequest_Content{} }
func (m *BidRequest_Content) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Content) ProtoMessage()    {}

func (m *BidRequest_Content) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *BidRequest_Content) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *BidRequest_Content) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *BidRequest_Content) GetArtist() string {
	if m != nil && m.Artist != nil {
		return *m.Artist
	}
	return ""
}

func (m *BidRequest_Content) GetAlbum() string {
	if m != nil && m.Album != nil {
		return *m.Album
	}
	return ""
}

func (m *BidRequest_Content) GetCat() []string {
	if m != nil {
		return m.Cat
	}
	return nil
}

func (m *BidRequest_Content) GetContext() BidRequest_ContextType {
	if m != nil && m.Context != nil {
		return *m.Context
	}
	return BidRequest_ContextType_Unkown
}

func (m *BidRequest_Content) GetAvlen() int32 {
	if m != nil && m.Avlen != nil {
		return *m.Avlen
	}
	return 0
}

func (m *BidRequest_Content) GetFirstChannel() []string {
	if m != nil {
		return m.FirstChannel
	}
	return nil
}

func (m *BidRequest_Content) GetSecondChannel() []string {
	if m != nil {
		return m.SecondChannel
	}
	return nil
}

// app对象
type BidRequest_App struct {
	Id               *string             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name             *string             `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Bundle           *string             `protobuf:"bytes,3,opt,name=bundle" json:"bundle,omitempty"`
	Ver              *string             `protobuf:"bytes,4,opt,name=ver" json:"ver,omitempty"`
	Cat              []string            `protobuf:"bytes,5,rep,name=cat" json:"cat,omitempty"`
	Keywords         []string            `protobuf:"bytes,6,rep,name=keywords" json:"keywords,omitempty"`
	Domain           *string             `protobuf:"bytes,7,opt,name=domain" json:"domain,omitempty"`
	Content          *BidRequest_Content `protobuf:"bytes,8,opt,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *BidRequest_App) Reset()         { *m = BidRequest_App{} }
func (m *BidRequest_App) String() string { return proto.CompactTextString(m) }
func (*BidRequest_App) ProtoMessage()    {}

func (m *BidRequest_App) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *BidRequest_App) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *BidRequest_App) GetBundle() string {
	if m != nil && m.Bundle != nil {
		return *m.Bundle
	}
	return ""
}

func (m *BidRequest_App) GetVer() string {
	if m != nil && m.Ver != nil {
		return *m.Ver
	}
	return ""
}

func (m *BidRequest_App) GetCat() []string {
	if m != nil {
		return m.Cat
	}
	return nil
}

func (m *BidRequest_App) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *BidRequest_App) GetDomain() string {
	if m != nil && m.Domain != nil {
		return *m.Domain
	}
	return ""
}

func (m *BidRequest_App) GetContent() *BidRequest_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

type BidRequest_Geo struct {
	Lat              *float32 `protobuf:"fixed32,1,opt,name=lat" json:"lat,omitempty"`
	Lon              *float32 `protobuf:"fixed32,2,opt,name=lon" json:"lon,omitempty"`
	Country          *string  `protobuf:"bytes,3,opt,name=country" json:"country,omitempty"`
	Region           *string  `protobuf:"bytes,4,opt,name=region" json:"region,omitempty"`
	City             *string  `protobuf:"bytes,5,opt,name=city" json:"city,omitempty"`
	Zip              *string  `protobuf:"bytes,6,opt,name=zip" json:"zip,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BidRequest_Geo) Reset()         { *m = BidRequest_Geo{} }
func (m *BidRequest_Geo) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Geo) ProtoMessage()    {}

func (m *BidRequest_Geo) GetLat() float32 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *BidRequest_Geo) GetLon() float32 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

func (m *BidRequest_Geo) GetCountry() string {
	if m != nil && m.Country != nil {
		return *m.Country
	}
	return ""
}

func (m *BidRequest_Geo) GetRegion() string {
	if m != nil && m.Region != nil {
		return *m.Region
	}
	return ""
}

func (m *BidRequest_Geo) GetCity() string {
	if m != nil && m.City != nil {
		return *m.City
	}
	return ""
}

func (m *BidRequest_Geo) GetZip() string {
	if m != nil && m.Zip != nil {
		return *m.Zip
	}
	return ""
}

type BidRequest_Device struct {
	Did    *string             `protobuf:"bytes,1,opt,name=did" json:"did,omitempty"`
	DidEnc *BidRequest_EncType `protobuf:"varint,2,opt,name=did_enc,enum=openrtb.BidRequest_EncType" json:"did_enc,omitempty"`
	// AndroidId或IDFA
	Dpid    *string             `protobuf:"bytes,3,opt,name=dpid" json:"dpid,omitempty"`
	DpidEnc *BidRequest_EncType `protobuf:"varint,4,opt,name=dpid_enc,enum=openrtb.BidRequest_EncType" json:"dpid_enc,omitempty"`
	// mac
	Mac    *string             `protobuf:"bytes,5,opt,name=mac" json:"mac,omitempty"`
	MacEnc *BidRequest_EncType `protobuf:"varint,6,opt,name=mac_enc,enum=openrtb.BidRequest_EncType" json:"mac_enc,omitempty"`
	// 设备浏览器的User-Agent字符串
	Ua *string `protobuf:"bytes,8,opt,name=ua" json:"ua,omitempty"`
	// geo对象
	Geo *BidRequest_Geo `protobuf:"bytes,9,opt,name=geo" json:"geo,omitempty"`
	// 设备ip
	Ip         *string                `protobuf:"bytes,10,opt,name=ip" json:"ip,omitempty"`
	DeviceType *BidRequest_DeviceType `protobuf:"varint,11,opt,name=device_type,enum=openrtb.BidRequest_DeviceType" json:"device_type,omitempty"`
	Make       *string                `protobuf:"bytes,12,opt,name=make" json:"make,omitempty"`
	Model      *string                `protobuf:"bytes,13,opt,name=model" json:"model,omitempty"`
	Os         *BidRequest_OsType     `protobuf:"varint,14,opt,name=os,enum=openrtb.BidRequest_OsType" json:"os,omitempty"`
	Osv        *string                `protobuf:"bytes,15,opt,name=osv" json:"osv,omitempty"`
	// 联网类型, 0:unknown, 1:wifi, 2:2g, 3:3g, 4:4g
	// optional int32 connection_type = 12;
	ConnectionType *BidRequest_ConnectionType `protobuf:"varint,16,opt,name=connection_type,enum=openrtb.BidRequest_ConnectionType" json:"connection_type,omitempty"`
	// 运营商代码，MCC+MNC
	Carrier          *string          `protobuf:"bytes,17,opt,name=carrier" json:"carrier,omitempty"`
	Language         *string          `protobuf:"bytes,18,opt,name=language" json:"language,omitempty"`
	Size             *BidRequest_Size `protobuf:"bytes,19,opt,name=size" json:"size,omitempty"`
	Ppi              *int32           `protobuf:"varint,20,opt,name=ppi" json:"ppi,omitempty"`
	IsApp            *bool            `protobuf:"varint,21,opt,name=isApp" json:"isApp,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *BidRequest_Device) Reset()         { *m = BidRequest_Device{} }
func (m *BidRequest_Device) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Device) ProtoMessage()    {}

func (m *BidRequest_Device) GetDid() string {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return ""
}

func (m *BidRequest_Device) GetDidEnc() BidRequest_EncType {
	if m != nil && m.DidEnc != nil {
		return *m.DidEnc
	}
	return BidRequest_EncType_Origin
}

func (m *BidRequest_Device) GetDpid() string {
	if m != nil && m.Dpid != nil {
		return *m.Dpid
	}
	return ""
}

func (m *BidRequest_Device) GetDpidEnc() BidRequest_EncType {
	if m != nil && m.DpidEnc != nil {
		return *m.DpidEnc
	}
	return BidRequest_EncType_Origin
}

func (m *BidRequest_Device) GetMac() string {
	if m != nil && m.Mac != nil {
		return *m.Mac
	}
	return ""
}

func (m *BidRequest_Device) GetMacEnc() BidRequest_EncType {
	if m != nil && m.MacEnc != nil {
		return *m.MacEnc
	}
	return BidRequest_EncType_Origin
}

func (m *BidRequest_Device) GetUa() string {
	if m != nil && m.Ua != nil {
		return *m.Ua
	}
	return ""
}

func (m *BidRequest_Device) GetGeo() *BidRequest_Geo {
	if m != nil {
		return m.Geo
	}
	return nil
}

func (m *BidRequest_Device) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *BidRequest_Device) GetDeviceType() BidRequest_DeviceType {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return BidRequest_DeviceType_Unknown
}

func (m *BidRequest_Device) GetMake() string {
	if m != nil && m.Make != nil {
		return *m.Make
	}
	return ""
}

func (m *BidRequest_Device) GetModel() string {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return ""
}

func (m *BidRequest_Device) GetOs() BidRequest_OsType {
	if m != nil && m.Os != nil {
		return *m.Os
	}
	return BidRequest_OsType_Android
}

func (m *BidRequest_Device) GetOsv() string {
	if m != nil && m.Osv != nil {
		return *m.Osv
	}
	return ""
}

func (m *BidRequest_Device) GetConnectionType() BidRequest_ConnectionType {
	if m != nil && m.ConnectionType != nil {
		return *m.ConnectionType
	}
	return BidRequest_ConnectionType_Unknown
}

func (m *BidRequest_Device) GetCarrier() string {
	if m != nil && m.Carrier != nil {
		return *m.Carrier
	}
	return ""
}

func (m *BidRequest_Device) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *BidRequest_Device) GetSize() *BidRequest_Size {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *BidRequest_Device) GetPpi() int32 {
	if m != nil && m.Ppi != nil {
		return *m.Ppi
	}
	return 0
}

func (m *BidRequest_Device) GetIsApp() bool {
	if m != nil && m.IsApp != nil {
		return *m.IsApp
	}
	return false
}

type BidRequest_User struct {
	Id       *string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Yob      *int32             `protobuf:"varint,2,opt,name=yob" json:"yob,omitempty"`
	Gender   *BidRequest_Gender `protobuf:"varint,3,opt,name=gender,enum=openrtb.BidRequest_Gender" json:"gender,omitempty"`
	Keywords []string           `protobuf:"bytes,4,rep,name=keywords" json:"keywords,omitempty"`
	// 用户设置的位置(home)
	Geo *BidRequest_Geo `protobuf:"bytes,5,opt,name=geo" json:"geo,omitempty"`
	// 年龄偏移值
	AgeOffset        *int32 `protobuf:"varint,6,opt,name=ageOffset" json:"ageOffset,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BidRequest_User) Reset()         { *m = BidRequest_User{} }
func (m *BidRequest_User) String() string { return proto.CompactTextString(m) }
func (*BidRequest_User) ProtoMessage()    {}

func (m *BidRequest_User) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *BidRequest_User) GetYob() int32 {
	if m != nil && m.Yob != nil {
		return *m.Yob
	}
	return 0
}

func (m *BidRequest_User) GetGender() BidRequest_Gender {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return BidRequest_Gender_Unkown
}

func (m *BidRequest_User) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *BidRequest_User) GetGeo() *BidRequest_Geo {
	if m != nil {
		return m.Geo
	}
	return nil
}

func (m *BidRequest_User) GetAgeOffset() int32 {
	if m != nil && m.AgeOffset != nil {
		return *m.AgeOffset
	}
	return 0
}

type BidRequest_Site struct {
	Id     *string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name   *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Domain *string  `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	Cat    []string `protobuf:"bytes,4,rep,name=cat" json:"cat,omitempty"`
	// URL of the page where the impression will be shown.
	Page             *string             `protobuf:"bytes,5,opt,name=page" json:"page,omitempty"`
	Ref              *string             `protobuf:"bytes,6,opt,name=ref" json:"ref,omitempty"`
	Keywords         []string            `protobuf:"bytes,7,rep,name=keywords" json:"keywords,omitempty"`
	Language         *string             `protobuf:"bytes,8,opt,name=language" json:"language,omitempty"`
	Content          *BidRequest_Content `protobuf:"bytes,9,opt,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *BidRequest_Site) Reset()         { *m = BidRequest_Site{} }
func (m *BidRequest_Site) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Site) ProtoMessage()    {}

func (m *BidRequest_Site) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *BidRequest_Site) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *BidRequest_Site) GetDomain() string {
	if m != nil && m.Domain != nil {
		return *m.Domain
	}
	return ""
}

func (m *BidRequest_Site) GetCat() []string {
	if m != nil {
		return m.Cat
	}
	return nil
}

func (m *BidRequest_Site) GetPage() string {
	if m != nil && m.Page != nil {
		return *m.Page
	}
	return ""
}

func (m *BidRequest_Site) GetRef() string {
	if m != nil && m.Ref != nil {
		return *m.Ref
	}
	return ""
}

func (m *BidRequest_Site) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *BidRequest_Site) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *BidRequest_Site) GetContent() *BidRequest_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

type BidResponse struct {
	Id               *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Bidid            *string                `protobuf:"bytes,2,opt,name=bidid" json:"bidid,omitempty"`
	Seatbids         []*BidResponse_SeatBid `protobuf:"bytes,3,rep,name=seatbids" json:"seatbids,omitempty"`
	Nbr              *int32                 `protobuf:"varint,4,opt,name=nbr" json:"nbr,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *BidResponse) Reset()         { *m = BidResponse{} }
func (m *BidResponse) String() string { return proto.CompactTextString(m) }
func (*BidResponse) ProtoMessage()    {}

func (m *BidResponse) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *BidResponse) GetBidid() string {
	if m != nil && m.Bidid != nil {
		return *m.Bidid
	}
	return ""
}

func (m *BidResponse) GetSeatbids() []*BidResponse_SeatBid {
	if m != nil {
		return m.Seatbids
	}
	return nil
}

func (m *BidResponse) GetNbr() int32 {
	if m != nil && m.Nbr != nil {
		return *m.Nbr
	}
	return 0
}

type BidResponse_Img struct {
	W                *int32  `protobuf:"varint,1,opt,name=w" json:"w,omitempty"`
	H                *int32  `protobuf:"varint,2,opt,name=h" json:"h,omitempty"`
	Url              *string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BidResponse_Img) Reset()         { *m = BidResponse_Img{} }
func (m *BidResponse_Img) String() string { return proto.CompactTextString(m) }
func (*BidResponse_Img) ProtoMessage()    {}

func (m *BidResponse_Img) GetW() int32 {
	if m != nil && m.W != nil {
		return *m.W
	}
	return 0
}

func (m *BidResponse_Img) GetH() int32 {
	if m != nil && m.H != nil {
		return *m.H
	}
	return 0
}

func (m *BidResponse_Img) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

type BidResponse_Text struct {
	Key              *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BidResponse_Text) Reset()         { *m = BidResponse_Text{} }
func (m *BidResponse_Text) String() string { return proto.CompactTextString(m) }
func (*BidResponse_Text) ProtoMessage()    {}

func (m *BidResponse_Text) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *BidResponse_Text) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type BidResponse_Video struct {
	W                *int32  `protobuf:"varint,1,opt,name=w" json:"w,omitempty"`
	H                *int32  `protobuf:"varint,2,opt,name=h" json:"h,omitempty"`
	Url              *string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BidResponse_Video) Reset()         { *m = BidResponse_Video{} }
func (m *BidResponse_Video) String() string { return proto.CompactTextString(m) }
func (*BidResponse_Video) ProtoMessage()    {}

func (m *BidResponse_Video) GetW() int32 {
	if m != nil && m.W != nil {
		return *m.W
	}
	return 0
}

func (m *BidResponse_Video) GetH() int32 {
	if m != nil && m.H != nil {
		return *m.H
	}
	return 0
}

func (m *BidResponse_Video) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

type BidResponse_Ext struct {
	Title            *string             `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Desc             *string             `protobuf:"bytes,2,opt,name=desc" json:"desc,omitempty"`
	Btname           *string             `protobuf:"bytes,3,opt,name=btname" json:"btname,omitempty"`
	Subtitle         *string             `protobuf:"bytes,4,opt,name=subtitle" json:"subtitle,omitempty"`
	MainImg          *BidResponse_Img    `protobuf:"bytes,5,opt,name=mainImg" json:"mainImg,omitempty"`
	Icon             *BidResponse_Img    `protobuf:"bytes,6,opt,name=icon" json:"icon,omitempty"`
	Logo             *BidResponse_Img    `protobuf:"bytes,7,opt,name=logo" json:"logo,omitempty"`
	ExtImg           []*BidResponse_Img  `protobuf:"bytes,8,rep,name=extImg" json:"extImg,omitempty"`
	ExtText          []*BidResponse_Text `protobuf:"bytes,9,rep,name=extText" json:"extText,omitempty"`
	Video            *BidResponse_Video  `protobuf:"bytes,10,opt,name=video" json:"video,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *BidResponse_Ext) Reset()         { *m = BidResponse_Ext{} }
func (m *BidResponse_Ext) String() string { return proto.CompactTextString(m) }
func (*BidResponse_Ext) ProtoMessage()    {}

func (m *BidResponse_Ext) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *BidResponse_Ext) GetDesc() string {
	if m != nil && m.Desc != nil {
		return *m.Desc
	}
	return ""
}

func (m *BidResponse_Ext) GetBtname() string {
	if m != nil && m.Btname != nil {
		return *m.Btname
	}
	return ""
}

func (m *BidResponse_Ext) GetSubtitle() string {
	if m != nil && m.Subtitle != nil {
		return *m.Subtitle
	}
	return ""
}

func (m *BidResponse_Ext) GetMainImg() *BidResponse_Img {
	if m != nil {
		return m.MainImg
	}
	return nil
}

func (m *BidResponse_Ext) GetIcon() *BidResponse_Img {
	if m != nil {
		return m.Icon
	}
	return nil
}

func (m *BidResponse_Ext) GetLogo() *BidResponse_Img {
	if m != nil {
		return m.Logo
	}
	return nil
}

func (m *BidResponse_Ext) GetExtImg() []*BidResponse_Img {
	if m != nil {
		return m.ExtImg
	}
	return nil
}

func (m *BidResponse_Ext) GetExtText() []*BidResponse_Text {
	if m != nil {
		return m.ExtText
	}
	return nil
}

func (m *BidResponse_Ext) GetVideo() *BidResponse_Video {
	if m != nil {
		return m.Video
	}
	return nil
}

type BidResponse_Event struct {
	Name             *BidResponse_EventName `protobuf:"varint,1,opt,name=name,enum=openrtb.BidResponse_EventName" json:"name,omitempty"`
	Value            []string               `protobuf:"bytes,2,rep,name=Value" json:"Value,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *BidResponse_Event) Reset()         { *m = BidResponse_Event{} }
func (m *BidResponse_Event) String() string { return proto.CompactTextString(m) }
func (*BidResponse_Event) ProtoMessage()    {}

func (m *BidResponse_Event) GetName() BidResponse_EventName {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return BidResponse_VideoTrack_FirstQuartile
}

func (m *BidResponse_Event) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type BidResponse_Bid struct {
	// dsp生成唯一id
	Id *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// 竞价价格
	Price *int32 `protobuf:"varint,2,opt,name=price" json:"price,omitempty"`
	// 广告id
	Adid        *int64           `protobuf:"varint,3,opt,name=adid" json:"adid,omitempty"`
	Impid       *string          `protobuf:"bytes,4,opt,name=impid" json:"impid,omitempty"`
	Ext         *BidResponse_Ext `protobuf:"bytes,5,opt,name=ext" json:"ext,omitempty"`
	Dealid      *string          `protobuf:"bytes,6,opt,name=dealid" json:"dealid,omitempty"`
	W           *int32           `protobuf:"varint,7,opt,name=w" json:"w,omitempty"`
	H           *int32           `protobuf:"varint,8,opt,name=h" json:"h,omitempty"`
	Cat         *string          `protobuf:"bytes,9,opt,name=cat" json:"cat,omitempty"`
	Adomain     *string          `protobuf:"bytes,10,opt,name=adomain" json:"adomain,omitempty"`
	ImpTrackers []string         `protobuf:"bytes,11,rep,name=impTrackers" json:"impTrackers,omitempty"`
	ClkTrackers []string         `protobuf:"bytes,12,rep,name=clkTrackers" json:"clkTrackers,omitempty"`
	// img url or video url
	Iurl *string `protobuf:"bytes,13,opt,name=iurl" json:"iurl,omitempty"`
	// creative attributes which describe the ad
	Attr       *BidResponse_Attr `protobuf:"varint,14,opt,name=attr,enum=openrtb.BidResponse_Attr" json:"attr,omitempty"`
	Adm        *string           `protobuf:"bytes,15,opt,name=adm" json:"adm,omitempty"`
	Templateid *string           `protobuf:"bytes,16,opt,name=templateid" json:"templateid,omitempty"`
	Ldp        *string           `protobuf:"bytes,17,opt,name=ldp" json:"ldp,omitempty"`
	// video play length
	Duration *int32 `protobuf:"varint,18,opt,name=duration" json:"duration,omitempty"`
	// Creative ID to assist with ad quality checking.
	Crid             *string              `protobuf:"bytes,19,opt,name=crid" json:"crid,omitempty"`
	Advertiserid     *int64               `protobuf:"varint,20,opt,name=advertiserid" json:"advertiserid,omitempty"`
	Deeplink         *string              `protobuf:"bytes,21,opt,name=deeplink" json:"deeplink,omitempty"`
	Events           []*BidResponse_Event `protobuf:"bytes,22,rep,name=events" json:"events,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *BidResponse_Bid) Reset()         { *m = BidResponse_Bid{} }
func (m *BidResponse_Bid) String() string { return proto.CompactTextString(m) }
func (*BidResponse_Bid) ProtoMessage()    {}

func (m *BidResponse_Bid) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *BidResponse_Bid) GetPrice() int32 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *BidResponse_Bid) GetAdid() int64 {
	if m != nil && m.Adid != nil {
		return *m.Adid
	}
	return 0
}

func (m *BidResponse_Bid) GetImpid() string {
	if m != nil && m.Impid != nil {
		return *m.Impid
	}
	return ""
}

func (m *BidResponse_Bid) GetExt() *BidResponse_Ext {
	if m != nil {
		return m.Ext
	}
	return nil
}

func (m *BidResponse_Bid) GetDealid() string {
	if m != nil && m.Dealid != nil {
		return *m.Dealid
	}
	return ""
}

func (m *BidResponse_Bid) GetW() int32 {
	if m != nil && m.W != nil {
		return *m.W
	}
	return 0
}

func (m *BidResponse_Bid) GetH() int32 {
	if m != nil && m.H != nil {
		return *m.H
	}
	return 0
}

func (m *BidResponse_Bid) GetCat() string {
	if m != nil && m.Cat != nil {
		return *m.Cat
	}
	return ""
}

func (m *BidResponse_Bid) GetAdomain() string {
	if m != nil && m.Adomain != nil {
		return *m.Adomain
	}
	return ""
}

func (m *BidResponse_Bid) GetImpTrackers() []string {
	if m != nil {
		return m.ImpTrackers
	}
	return nil
}

func (m *BidResponse_Bid) GetClkTrackers() []string {
	if m != nil {
		return m.ClkTrackers
	}
	return nil
}

func (m *BidResponse_Bid) GetIurl() string {
	if m != nil && m.Iurl != nil {
		return *m.Iurl
	}
	return ""
}

func (m *BidResponse_Bid) GetAttr() BidResponse_Attr {
	if m != nil && m.Attr != nil {
		return *m.Attr
	}
	return BidResponse_Attr_Web
}

func (m *BidResponse_Bid) GetAdm() string {
	if m != nil && m.Adm != nil {
		return *m.Adm
	}
	return ""
}

func (m *BidResponse_Bid) GetTemplateid() string {
	if m != nil && m.Templateid != nil {
		return *m.Templateid
	}
	return ""
}

func (m *BidResponse_Bid) GetLdp() string {
	if m != nil && m.Ldp != nil {
		return *m.Ldp
	}
	return ""
}

func (m *BidResponse_Bid) GetDuration() int32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *BidResponse_Bid) GetCrid() string {
	if m != nil && m.Crid != nil {
		return *m.Crid
	}
	return ""
}

func (m *BidResponse_Bid) GetAdvertiserid() int64 {
	if m != nil && m.Advertiserid != nil {
		return *m.Advertiserid
	}
	return 0
}

func (m *BidResponse_Bid) GetDeeplink() string {
	if m != nil && m.Deeplink != nil {
		return *m.Deeplink
	}
	return ""
}

func (m *BidResponse_Bid) GetEvents() []*BidResponse_Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type BidResponse_SeatBid struct {
	SeatId           *string            `protobuf:"bytes,1,opt,name=seatId" json:"seatId,omitempty"`
	Bid              []*BidResponse_Bid `protobuf:"bytes,2,rep,name=bid" json:"bid,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *BidResponse_SeatBid) Reset()         { *m = BidResponse_SeatBid{} }
func (m *BidResponse_SeatBid) String() string { return proto.CompactTextString(m) }
func (*BidResponse_SeatBid) ProtoMessage()    {}

func (m *BidResponse_SeatBid) GetSeatId() string {
	if m != nil && m.SeatId != nil {
		return *m.SeatId
	}
	return ""
}

func (m *BidResponse_SeatBid) GetBid() []*BidResponse_Bid {
	if m != nil {
		return m.Bid
	}
	return nil
}

func init() {
	proto.RegisterType((*BidRequest)(nil), "openrtb.BidRequest")
	proto.RegisterType((*BidRequest_Size)(nil), "openrtb.BidRequest.Size")
	proto.RegisterType((*BidRequest_Format)(nil), "openrtb.BidRequest.Format")
	proto.RegisterType((*BidRequest_Banner)(nil), "openrtb.BidRequest.Banner")
	proto.RegisterType((*BidRequest_ImageAsset)(nil), "openrtb.BidRequest.ImageAsset")
	proto.RegisterType((*BidRequest_VideoAsset)(nil), "openrtb.BidRequest.VideoAsset")
	proto.RegisterType((*BidRequest_Asset)(nil), "openrtb.BidRequest.Asset")
	proto.RegisterType((*BidRequest_Native)(nil), "openrtb.BidRequest.Native")
	proto.RegisterType((*BidRequest_Video)(nil), "openrtb.BidRequest.Video")
	proto.RegisterType((*BidRequest_Metric)(nil), "openrtb.BidRequest.Metric")
	proto.RegisterType((*BidRequest_Impression)(nil), "openrtb.BidRequest.Impression")
	proto.RegisterType((*BidRequest_Content)(nil), "openrtb.BidRequest.Content")
	proto.RegisterType((*BidRequest_App)(nil), "openrtb.BidRequest.App")
	proto.RegisterType((*BidRequest_Geo)(nil), "openrtb.BidRequest.Geo")
	proto.RegisterType((*BidRequest_Device)(nil), "openrtb.BidRequest.Device")
	proto.RegisterType((*BidRequest_User)(nil), "openrtb.BidRequest.User")
	proto.RegisterType((*BidRequest_Site)(nil), "openrtb.BidRequest.Site")
	proto.RegisterType((*BidResponse)(nil), "openrtb.BidResponse")
	proto.RegisterType((*BidResponse_Img)(nil), "openrtb.BidResponse.Img")
	proto.RegisterType((*BidResponse_Text)(nil), "openrtb.BidResponse.Text")
	proto.RegisterType((*BidResponse_Video)(nil), "openrtb.BidResponse.Video")
	proto.RegisterType((*BidResponse_Ext)(nil), "openrtb.BidResponse.Ext")
	proto.RegisterType((*BidResponse_Event)(nil), "openrtb.BidResponse.Event")
	proto.RegisterType((*BidResponse_Bid)(nil), "openrtb.BidResponse.Bid")
	proto.RegisterType((*BidResponse_SeatBid)(nil), "openrtb.BidResponse.SeatBid")
	proto.RegisterEnum("openrtb.BidRequest_DeviceType", BidRequest_DeviceType_name, BidRequest_DeviceType_value)
	proto.RegisterEnum("openrtb.BidRequest_OsType", BidRequest_OsType_name, BidRequest_OsType_value)
	proto.RegisterEnum("openrtb.BidRequest_ConnectionType", BidRequest_ConnectionType_name, BidRequest_ConnectionType_value)
	proto.RegisterEnum("openrtb.BidRequest_Gender", BidRequest_Gender_name, BidRequest_Gender_value)
	proto.RegisterEnum("openrtb.BidRequest_SlotType", BidRequest_SlotType_name, BidRequest_SlotType_value)
	proto.RegisterEnum("openrtb.BidRequest_EncType", BidRequest_EncType_name, BidRequest_EncType_value)
	proto.RegisterEnum("openrtb.BidRequest_SaleMode", BidRequest_SaleMode_name, BidRequest_SaleMode_value)
	proto.RegisterEnum("openrtb.BidRequest_ImageType", BidRequest_ImageType_name, BidRequest_ImageType_value)
	proto.RegisterEnum("openrtb.BidRequest_ContextType", BidRequest_ContextType_name, BidRequest_ContextType_value)
	proto.RegisterEnum("openrtb.BidRequest_Video_VideoLinearity", BidRequest_Video_VideoLinearity_name, BidRequest_Video_VideoLinearity_value)
	proto.RegisterEnum("openrtb.BidRequest_Video_PlaybackMethod", BidRequest_Video_PlaybackMethod_name, BidRequest_Video_PlaybackMethod_value)
	proto.RegisterEnum("openrtb.BidResponse_EventName", BidResponse_EventName_name, BidResponse_EventName_value)
	proto.RegisterEnum("openrtb.BidResponse_Attr", BidResponse_Attr_name, BidResponse_Attr_value)
}
