// Code generated by protoc-gen-go.
// source: gdt.proto
// DO NOT EDIT!

/*
Package gdt is a generated protocol buffer package.

It is generated from these files:
	gdt.proto

It has these top-level messages:
	BidRequest
	BidResponse
*/
package gdt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type BidRequest_DeviceType int32

const (
	BidRequest_DEVICETYPE_UNKNOWN BidRequest_DeviceType = 0
	BidRequest_DEVICETYPE_PC      BidRequest_DeviceType = 1
	BidRequest_DEVICETYPE_MOBILE  BidRequest_DeviceType = 2
	BidRequest_DEVICETYPE_PAD     BidRequest_DeviceType = 3
)

var BidRequest_DeviceType_name = map[int32]string{
	0: "DEVICETYPE_UNKNOWN",
	1: "DEVICETYPE_PC",
	2: "DEVICETYPE_MOBILE",
	3: "DEVICETYPE_PAD",
}
var BidRequest_DeviceType_value = map[string]int32{
	"DEVICETYPE_UNKNOWN": 0,
	"DEVICETYPE_PC":      1,
	"DEVICETYPE_MOBILE":  2,
	"DEVICETYPE_PAD":     3,
}

func (x BidRequest_DeviceType) Enum() *BidRequest_DeviceType {
	p := new(BidRequest_DeviceType)
	*p = x
	return p
}
func (x BidRequest_DeviceType) String() string {
	return proto.EnumName(BidRequest_DeviceType_name, int32(x))
}
func (x *BidRequest_DeviceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_DeviceType_value, data, "BidRequest_DeviceType")
	if err != nil {
		return err
	}
	*x = BidRequest_DeviceType(value)
	return nil
}

type BidRequest_Carrier int32

const (
	BidRequest_CARRIER_UNKNOWN      BidRequest_Carrier = 0
	BidRequest_CARRIER_CHINAMOBILE  BidRequest_Carrier = 1
	BidRequest_CARRIER_CHINAUNICOM  BidRequest_Carrier = 2
	BidRequest_CARRIER_CHINATELECOM BidRequest_Carrier = 3
)

var BidRequest_Carrier_name = map[int32]string{
	0: "CARRIER_UNKNOWN",
	1: "CARRIER_CHINAMOBILE",
	2: "CARRIER_CHINAUNICOM",
	3: "CARRIER_CHINATELECOM",
}
var BidRequest_Carrier_value = map[string]int32{
	"CARRIER_UNKNOWN":      0,
	"CARRIER_CHINAMOBILE":  1,
	"CARRIER_CHINAUNICOM":  2,
	"CARRIER_CHINATELECOM": 3,
}

func (x BidRequest_Carrier) Enum() *BidRequest_Carrier {
	p := new(BidRequest_Carrier)
	*p = x
	return p
}
func (x BidRequest_Carrier) String() string {
	return proto.EnumName(BidRequest_Carrier_name, int32(x))
}
func (x *BidRequest_Carrier) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_Carrier_value, data, "BidRequest_Carrier")
	if err != nil {
		return err
	}
	*x = BidRequest_Carrier(value)
	return nil
}

type BidRequest_ConnectionType int32

const (
	BidRequest_CONNECTIONTYPE_UNKNOWN BidRequest_ConnectionType = 0
	BidRequest_CONNECTIONTYPE_WIFI    BidRequest_ConnectionType = 1
	BidRequest_CONNECTIONTYPE_2G      BidRequest_ConnectionType = 2
	BidRequest_CONNECTIONTYPE_3G      BidRequest_ConnectionType = 3
	BidRequest_CONNECTIONTYPE_4G      BidRequest_ConnectionType = 4
)

var BidRequest_ConnectionType_name = map[int32]string{
	0: "CONNECTIONTYPE_UNKNOWN",
	1: "CONNECTIONTYPE_WIFI",
	2: "CONNECTIONTYPE_2G",
	3: "CONNECTIONTYPE_3G",
	4: "CONNECTIONTYPE_4G",
}
var BidRequest_ConnectionType_value = map[string]int32{
	"CONNECTIONTYPE_UNKNOWN": 0,
	"CONNECTIONTYPE_WIFI":    1,
	"CONNECTIONTYPE_2G":      2,
	"CONNECTIONTYPE_3G":      3,
	"CONNECTIONTYPE_4G":      4,
}

func (x BidRequest_ConnectionType) Enum() *BidRequest_ConnectionType {
	p := new(BidRequest_ConnectionType)
	*p = x
	return p
}
func (x BidRequest_ConnectionType) String() string {
	return proto.EnumName(BidRequest_ConnectionType_name, int32(x))
}
func (x *BidRequest_ConnectionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_ConnectionType_value, data, "BidRequest_ConnectionType")
	if err != nil {
		return err
	}
	*x = BidRequest_ConnectionType(value)
	return nil
}

type BidRequest_OperatingSystem int32

const (
	BidRequest_OS_UNKNOWN BidRequest_OperatingSystem = 0
	BidRequest_OS_IOS     BidRequest_OperatingSystem = 1
	BidRequest_OS_ANDROID BidRequest_OperatingSystem = 2
	BidRequest_OS_WINDOWS BidRequest_OperatingSystem = 3
	BidRequest_OS_SYMBIAN BidRequest_OperatingSystem = 4
	BidRequest_OS_JAVA    BidRequest_OperatingSystem = 5
)

var BidRequest_OperatingSystem_name = map[int32]string{
	0: "OS_UNKNOWN",
	1: "OS_IOS",
	2: "OS_ANDROID",
	3: "OS_WINDOWS",
	4: "OS_SYMBIAN",
	5: "OS_JAVA",
}
var BidRequest_OperatingSystem_value = map[string]int32{
	"OS_UNKNOWN": 0,
	"OS_IOS":     1,
	"OS_ANDROID": 2,
	"OS_WINDOWS": 3,
	"OS_SYMBIAN": 4,
	"OS_JAVA":    5,
}

func (x BidRequest_OperatingSystem) Enum() *BidRequest_OperatingSystem {
	p := new(BidRequest_OperatingSystem)
	*p = x
	return p
}
func (x BidRequest_OperatingSystem) String() string {
	return proto.EnumName(BidRequest_OperatingSystem_name, int32(x))
}
func (x *BidRequest_OperatingSystem) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_OperatingSystem_value, data, "BidRequest_OperatingSystem")
	if err != nil {
		return err
	}
	*x = BidRequest_OperatingSystem(value)
	return nil
}

// 原生广告位要素
type BidRequest_Impression_Native_Fields int32

const (
	// 标题，应用名称
	BidRequest_Impression_Native_HEADLINE BidRequest_Impression_Native_Fields = 1
	// 图标，应用图标
	BidRequest_Impression_Native_ICON BidRequest_Impression_Native_Fields = 2
	// 主图
	BidRequest_Impression_Native_IMAGE BidRequest_Impression_Native_Fields = 4
	// 描述
	BidRequest_Impression_Native_DESCRIPTION BidRequest_Impression_Native_Fields = 8
)

var BidRequest_Impression_Native_Fields_name = map[int32]string{
	1: "HEADLINE",
	2: "ICON",
	4: "IMAGE",
	8: "DESCRIPTION",
}
var BidRequest_Impression_Native_Fields_value = map[string]int32{
	"HEADLINE":    1,
	"ICON":        2,
	"IMAGE":       4,
	"DESCRIPTION": 8,
}

func (x BidRequest_Impression_Native_Fields) Enum() *BidRequest_Impression_Native_Fields {
	p := new(BidRequest_Impression_Native_Fields)
	*p = x
	return p
}
func (x BidRequest_Impression_Native_Fields) String() string {
	return proto.EnumName(BidRequest_Impression_Native_Fields_name, int32(x))
}
func (x *BidRequest_Impression_Native_Fields) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_Impression_Native_Fields_value, data, "BidRequest_Impression_Native_Fields")
	if err != nil {
		return err
	}
	*x = BidRequest_Impression_Native_Fields(value)
	return nil
}

// 原生广告类型
type BidRequest_Impression_Native_Type int32

const (
	// 普链
	BidRequest_Impression_Native_LINK BidRequest_Impression_Native_Type = 0
	// 应用
	BidRequest_Impression_Native_APP BidRequest_Impression_Native_Type = 1
)

var BidRequest_Impression_Native_Type_name = map[int32]string{
	0: "LINK",
	1: "APP",
}
var BidRequest_Impression_Native_Type_value = map[string]int32{
	"LINK": 0,
	"APP":  1,
}

func (x BidRequest_Impression_Native_Type) Enum() *BidRequest_Impression_Native_Type {
	p := new(BidRequest_Impression_Native_Type)
	*p = x
	return p
}
func (x BidRequest_Impression_Native_Type) String() string {
	return proto.EnumName(BidRequest_Impression_Native_Type_name, int32(x))
}
func (x *BidRequest_Impression_Native_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_Impression_Native_Type_value, data, "BidRequest_Impression_Native_Type")
	if err != nil {
		return err
	}
	*x = BidRequest_Impression_Native_Type(value)
	return nil
}

type BidRequest_User_Demographic_Gender int32

const (
	BidRequest_User_Demographic_GENDER_UNKNOWN BidRequest_User_Demographic_Gender = 0
	BidRequest_User_Demographic_GENDER_MALE    BidRequest_User_Demographic_Gender = 1
	BidRequest_User_Demographic_GENDER_FEMALE  BidRequest_User_Demographic_Gender = 2
)

var BidRequest_User_Demographic_Gender_name = map[int32]string{
	0: "GENDER_UNKNOWN",
	1: "GENDER_MALE",
	2: "GENDER_FEMALE",
}
var BidRequest_User_Demographic_Gender_value = map[string]int32{
	"GENDER_UNKNOWN": 0,
	"GENDER_MALE":    1,
	"GENDER_FEMALE":  2,
}

func (x BidRequest_User_Demographic_Gender) Enum() *BidRequest_User_Demographic_Gender {
	p := new(BidRequest_User_Demographic_Gender)
	*p = x
	return p
}
func (x BidRequest_User_Demographic_Gender) String() string {
	return proto.EnumName(BidRequest_User_Demographic_Gender_name, int32(x))
}
func (x *BidRequest_User_Demographic_Gender) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_User_Demographic_Gender_value, data, "BidRequest_User_Demographic_Gender")
	if err != nil {
		return err
	}
	*x = BidRequest_User_Demographic_Gender(value)
	return nil
}

// 学历
type BidRequest_User_Demographic_Education int32

const (
	BidRequest_User_Demographic_EDUCATION_UNKNOWN        BidRequest_User_Demographic_Education = 0
	BidRequest_User_Demographic_EDUCATION_DOCTOR         BidRequest_User_Demographic_Education = 1
	BidRequest_User_Demographic_EDUCATION_MASTER         BidRequest_User_Demographic_Education = 2
	BidRequest_User_Demographic_EDUCATION_COLLEGE        BidRequest_User_Demographic_Education = 3
	BidRequest_User_Demographic_EDUCATION_HIGH_SCHOOL    BidRequest_User_Demographic_Education = 4
	BidRequest_User_Demographic_EDUCATION_MIDDLE_SCHOOL  BidRequest_User_Demographic_Education = 5
	BidRequest_User_Demographic_EDUCATION_PRIMARY_SCHOOL BidRequest_User_Demographic_Education = 6
)

var BidRequest_User_Demographic_Education_name = map[int32]string{
	0: "EDUCATION_UNKNOWN",
	1: "EDUCATION_DOCTOR",
	2: "EDUCATION_MASTER",
	3: "EDUCATION_COLLEGE",
	4: "EDUCATION_HIGH_SCHOOL",
	5: "EDUCATION_MIDDLE_SCHOOL",
	6: "EDUCATION_PRIMARY_SCHOOL",
}
var BidRequest_User_Demographic_Education_value = map[string]int32{
	"EDUCATION_UNKNOWN":        0,
	"EDUCATION_DOCTOR":         1,
	"EDUCATION_MASTER":         2,
	"EDUCATION_COLLEGE":        3,
	"EDUCATION_HIGH_SCHOOL":    4,
	"EDUCATION_MIDDLE_SCHOOL":  5,
	"EDUCATION_PRIMARY_SCHOOL": 6,
}

func (x BidRequest_User_Demographic_Education) Enum() *BidRequest_User_Demographic_Education {
	p := new(BidRequest_User_Demographic_Education)
	*p = x
	return p
}
func (x BidRequest_User_Demographic_Education) String() string {
	return proto.EnumName(BidRequest_User_Demographic_Education_name, int32(x))
}
func (x *BidRequest_User_Demographic_Education) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_User_Demographic_Education_value, data, "BidRequest_User_Demographic_Education")
	if err != nil {
		return err
	}
	*x = BidRequest_User_Demographic_Education(value)
	return nil
}

type BidRequest_User_Demographic_ConsumptionAbilityLevel int32

const (
	BidRequest_User_Demographic_CONSUMPTION_ABILITY_LEVEL_UNKNOWN BidRequest_User_Demographic_ConsumptionAbilityLevel = 0
	BidRequest_User_Demographic_CONSUMPTION_ABILITY_LEVEL_HIGH    BidRequest_User_Demographic_ConsumptionAbilityLevel = 1
	BidRequest_User_Demographic_CONSUMPTION_ABILITY_LEVEL_LOW     BidRequest_User_Demographic_ConsumptionAbilityLevel = 2
)

var BidRequest_User_Demographic_ConsumptionAbilityLevel_name = map[int32]string{
	0: "CONSUMPTION_ABILITY_LEVEL_UNKNOWN",
	1: "CONSUMPTION_ABILITY_LEVEL_HIGH",
	2: "CONSUMPTION_ABILITY_LEVEL_LOW",
}
var BidRequest_User_Demographic_ConsumptionAbilityLevel_value = map[string]int32{
	"CONSUMPTION_ABILITY_LEVEL_UNKNOWN": 0,
	"CONSUMPTION_ABILITY_LEVEL_HIGH":    1,
	"CONSUMPTION_ABILITY_LEVEL_LOW":     2,
}

func (x BidRequest_User_Demographic_ConsumptionAbilityLevel) Enum() *BidRequest_User_Demographic_ConsumptionAbilityLevel {
	p := new(BidRequest_User_Demographic_ConsumptionAbilityLevel)
	*p = x
	return p
}
func (x BidRequest_User_Demographic_ConsumptionAbilityLevel) String() string {
	return proto.EnumName(BidRequest_User_Demographic_ConsumptionAbilityLevel_name, int32(x))
}
func (x *BidRequest_User_Demographic_ConsumptionAbilityLevel) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_User_Demographic_ConsumptionAbilityLevel_value, data, "BidRequest_User_Demographic_ConsumptionAbilityLevel")
	if err != nil {
		return err
	}
	*x = BidRequest_User_Demographic_ConsumptionAbilityLevel(value)
	return nil
}

// 婚姻状况
type BidRequest_User_Demographic_MarriageStatus int32

const (
	BidRequest_User_Demographic_MARRIAGE_STATUS_UNKNOWN    BidRequest_User_Demographic_MarriageStatus = 0
	BidRequest_User_Demographic_MARRIAGE_STATUS_SINGLE     BidRequest_User_Demographic_MarriageStatus = 1
	BidRequest_User_Demographic_MARRIAGE_STATUS_HAVE_BABY  BidRequest_User_Demographic_MarriageStatus = 2
	BidRequest_User_Demographic_MARRIAGE_STATUS_NEWLY_WEDS BidRequest_User_Demographic_MarriageStatus = 3
	BidRequest_User_Demographic_MARRIAGE_STATUS_IN_LOVE    BidRequest_User_Demographic_MarriageStatus = 4
	BidRequest_User_Demographic_MARRIAGE_STATUS_HAVE_KID   BidRequest_User_Demographic_MarriageStatus = 5
	BidRequest_User_Demographic_MARRIAGE_STATUS_MARRIED    BidRequest_User_Demographic_MarriageStatus = 6
	BidRequest_User_Demographic_MARRIAGE_STATUS_SECRET     BidRequest_User_Demographic_MarriageStatus = 7
	BidRequest_User_Demographic_MARRIAGE_STATUS_ENGAGED    BidRequest_User_Demographic_MarriageStatus = 8
	BidRequest_User_Demographic_MARRIAGE_STATUS_SEPARATED  BidRequest_User_Demographic_MarriageStatus = 9
	BidRequest_User_Demographic_MARRIAGE_STATUS_DIVORCED   BidRequest_User_Demographic_MarriageStatus = 10
)

var BidRequest_User_Demographic_MarriageStatus_name = map[int32]string{
	0:  "MARRIAGE_STATUS_UNKNOWN",
	1:  "MARRIAGE_STATUS_SINGLE",
	2:  "MARRIAGE_STATUS_HAVE_BABY",
	3:  "MARRIAGE_STATUS_NEWLY_WEDS",
	4:  "MARRIAGE_STATUS_IN_LOVE",
	5:  "MARRIAGE_STATUS_HAVE_KID",
	6:  "MARRIAGE_STATUS_MARRIED",
	7:  "MARRIAGE_STATUS_SECRET",
	8:  "MARRIAGE_STATUS_ENGAGED",
	9:  "MARRIAGE_STATUS_SEPARATED",
	10: "MARRIAGE_STATUS_DIVORCED",
}
var BidRequest_User_Demographic_MarriageStatus_value = map[string]int32{
	"MARRIAGE_STATUS_UNKNOWN":    0,
	"MARRIAGE_STATUS_SINGLE":     1,
	"MARRIAGE_STATUS_HAVE_BABY":  2,
	"MARRIAGE_STATUS_NEWLY_WEDS": 3,
	"MARRIAGE_STATUS_IN_LOVE":    4,
	"MARRIAGE_STATUS_HAVE_KID":   5,
	"MARRIAGE_STATUS_MARRIED":    6,
	"MARRIAGE_STATUS_SECRET":     7,
	"MARRIAGE_STATUS_ENGAGED":    8,
	"MARRIAGE_STATUS_SEPARATED":  9,
	"MARRIAGE_STATUS_DIVORCED":   10,
}

func (x BidRequest_User_Demographic_MarriageStatus) Enum() *BidRequest_User_Demographic_MarriageStatus {
	p := new(BidRequest_User_Demographic_MarriageStatus)
	*p = x
	return p
}
func (x BidRequest_User_Demographic_MarriageStatus) String() string {
	return proto.EnumName(BidRequest_User_Demographic_MarriageStatus_name, int32(x))
}
func (x *BidRequest_User_Demographic_MarriageStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_User_Demographic_MarriageStatus_value, data, "BidRequest_User_Demographic_MarriageStatus")
	if err != nil {
		return err
	}
	*x = BidRequest_User_Demographic_MarriageStatus(value)
	return nil
}

type BidRequest struct {
	// ADX提供的BidRequest唯一标识
	Id *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// true表示探测网络延迟，不触发竞价逻辑
	// DSP设置request_id和processing_time_ms后立即返回BidResponse
	// DSP必须支持此特性
	IsPing *bool `protobuf:"varint,2,opt,name=is_ping,def=0" json:"is_ping,omitempty"`
	// true表示测试请求，竞价成功的广告不会被展示和计费
	// DSP对此类请求的处理完全同普通请求
	// DSP必须支持此特性
	IsTest      *bool                    `protobuf:"varint,3,opt,name=is_test,def=0" json:"is_test,omitempty"`
	Impressions []*BidRequest_Impression `protobuf:"bytes,4,rep,name=impressions" json:"impressions,omitempty"`
	Device      *BidRequest_Device       `protobuf:"bytes,5,opt,name=device" json:"device,omitempty"`
	// 设备联网IP
	Ip *string `protobuf:"bytes,6,opt,name=ip" json:"ip,omitempty"`
	// 部分流量上可能没有有效IP，此时用地域码做定向
	// 取值见《广点通地域码》
	AreaCode *int32           `protobuf:"varint,7,opt,name=area_code" json:"area_code,omitempty"`
	User     *BidRequest_User `protobuf:"bytes,8,opt,name=user" json:"user,omitempty"`
	Geo      *BidRequest_Geo  `protobuf:"bytes,9,opt,name=geo" json:"geo,omitempty"`
	App      *BidRequest_App  `protobuf:"bytes,10,opt,name=app" json:"app,omitempty"`
	// 广告主的Boss QQ号
	BossQq *uint64 `protobuf:"varint,11,opt,name=boss_qq" json:"boss_qq,omitempty"`
	// 是否支持应用直达, 请求级别的属性
	SupportDeepLink  *bool                     `protobuf:"varint,12,opt,name=support_deep_link,def=0" json:"support_deep_link,omitempty"`
	WxFlowClass      []uint64                  `protobuf:"varint,13,rep,name=wx_flow_class" json:"wx_flow_class,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *BidRequest) Reset()         { *m = BidRequest{} }
func (m *BidRequest) String() string { return proto.CompactTextString(m) }
func (*BidRequest) ProtoMessage()    {}

var extRange_BidRequest = []proto.ExtensionRange{
	{10000, 536870911},
}

func (*BidRequest) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_BidRequest
}
func (m *BidRequest) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

const Default_BidRequest_IsPing bool = false
const Default_BidRequest_IsTest bool = false
const Default_BidRequest_SupportDeepLink bool = false

func (m *BidRequest) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *BidRequest) GetIsPing() bool {
	if m != nil && m.IsPing != nil {
		return *m.IsPing
	}
	return Default_BidRequest_IsPing
}

func (m *BidRequest) GetIsTest() bool {
	if m != nil && m.IsTest != nil {
		return *m.IsTest
	}
	return Default_BidRequest_IsTest
}

func (m *BidRequest) GetImpressions() []*BidRequest_Impression {
	if m != nil {
		return m.Impressions
	}
	return nil
}

func (m *BidRequest) GetDevice() *BidRequest_Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *BidRequest) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *BidRequest) GetAreaCode() int32 {
	if m != nil && m.AreaCode != nil {
		return *m.AreaCode
	}
	return 0
}

func (m *BidRequest) GetUser() *BidRequest_User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *BidRequest) GetGeo() *BidRequest_Geo {
	if m != nil {
		return m.Geo
	}
	return nil
}

func (m *BidRequest) GetApp() *BidRequest_App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *BidRequest) GetBossQq() uint64 {
	if m != nil && m.BossQq != nil {
		return *m.BossQq
	}
	return 0
}

func (m *BidRequest) GetSupportDeepLink() bool {
	if m != nil && m.SupportDeepLink != nil {
		return *m.SupportDeepLink
	}
	return Default_BidRequest_SupportDeepLink
}

func (m *BidRequest) GetWxFlowClass() []uint64 {
	if m != nil {
		return m.WxFlowClass
	}
	return nil
}

type BidRequest_Impression struct {
	// BidRequest范围内，Impression唯一标识
	Id *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// ADX提供的广告位id
	PlacementId *int64 `protobuf:"varint,2,opt,name=placement_id" json:"placement_id,omitempty"`
	// 广告位支持的素材规格列表
	// 取值见《广告样式说明.xlsx 》
	CreativeSpecs []int32 `protobuf:"varint,3,rep,name=creative_specs" json:"creative_specs,omitempty"`
	// 广告位底价，CPM，单位:分
	BidFloor *int32 `protobuf:"varint,4,opt,name=bid_floor" json:"bid_floor,omitempty"`
	// 广告位过滤的行业ID列表
	// 取值见《广告主行业分类.xlsx》
	BlockingIndustryId []int64                         `protobuf:"varint,5,rep,name=blocking_industry_id" json:"blocking_industry_id,omitempty"`
	Natives            []*BidRequest_Impression_Native `protobuf:"bytes,6,rep,name=natives" json:"natives,omitempty"`
	// CPD或者合约CPM的合同号（已废弃）
	ContractCode []string `protobuf:"bytes,7,rep,name=contract_code" json:"contract_code,omitempty"`
	// 广告位支持的素材类型列表，比如jpeg，gif等, 为空的时候不做限制
	MultimediaTypeWhiteList []string `protobuf:"bytes,8,rep,name=multimedia_type_white_list" json:"multimedia_type_white_list,omitempty"`
	// 广告位过滤的关键字
	BlockingKeyword []string `protobuf:"bytes,10,rep,name=blocking_keyword" json:"blocking_keyword,omitempty"`
	// 当advertiser_whitelist非空时，adx只接受白名单广告主的广告
	AdvertiserWhitelist []string `protobuf:"bytes,11,rep,name=advertiser_whitelist" json:"advertiser_whitelist,omitempty"`
	// 广告位过滤的广告主
	AdvertiserBlacklist []string `protobuf:"bytes,12,rep,name=advertiser_blacklist" json:"advertiser_blacklist,omitempty"`
	// 命中的pretargeting配置的id
	PretargetingIds []string `protobuf:"bytes,13,rep,name=pretargeting_ids" json:"pretargeting_ids,omitempty"`
	// preferred deal使用的deal id
	DealIds          []string `protobuf:"bytes,14,rep,name=deal_ids" json:"deal_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BidRequest_Impression) Reset()         { *m = BidRequest_Impression{} }
func (m *BidRequest_Impression) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Impression) ProtoMessage()    {}

func (m *BidRequest_Impression) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *BidRequest_Impression) GetPlacementId() int64 {
	if m != nil && m.PlacementId != nil {
		return *m.PlacementId
	}
	return 0
}

func (m *BidRequest_Impression) GetCreativeSpecs() []int32 {
	if m != nil {
		return m.CreativeSpecs
	}
	return nil
}

func (m *BidRequest_Impression) GetBidFloor() int32 {
	if m != nil && m.BidFloor != nil {
		return *m.BidFloor
	}
	return 0
}

func (m *BidRequest_Impression) GetBlockingIndustryId() []int64 {
	if m != nil {
		return m.BlockingIndustryId
	}
	return nil
}

func (m *BidRequest_Impression) GetNatives() []*BidRequest_Impression_Native {
	if m != nil {
		return m.Natives
	}
	return nil
}

func (m *BidRequest_Impression) GetContractCode() []string {
	if m != nil {
		return m.ContractCode
	}
	return nil
}

func (m *BidRequest_Impression) GetMultimediaTypeWhiteList() []string {
	if m != nil {
		return m.MultimediaTypeWhiteList
	}
	return nil
}

func (m *BidRequest_Impression) GetBlockingKeyword() []string {
	if m != nil {
		return m.BlockingKeyword
	}
	return nil
}

func (m *BidRequest_Impression) GetAdvertiserWhitelist() []string {
	if m != nil {
		return m.AdvertiserWhitelist
	}
	return nil
}

func (m *BidRequest_Impression) GetAdvertiserBlacklist() []string {
	if m != nil {
		return m.AdvertiserBlacklist
	}
	return nil
}

func (m *BidRequest_Impression) GetPretargetingIds() []string {
	if m != nil {
		return m.PretargetingIds
	}
	return nil
}

func (m *BidRequest_Impression) GetDealIds() []string {
	if m != nil {
		return m.DealIds
	}
	return nil
}

// 原生广告位信息
type BidRequest_Impression_Native struct {
	// 所需要的原生广告位要素，按照比特位填充
	RequiredFields   *uint64                            `protobuf:"varint,1,opt,name=required_fields" json:"required_fields,omitempty"`
	Type             *BidRequest_Impression_Native_Type `protobuf:"varint,2,opt,name=type,enum=gdt.BidRequest_Impression_Native_Type" json:"type,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *BidRequest_Impression_Native) Reset()         { *m = BidRequest_Impression_Native{} }
func (m *BidRequest_Impression_Native) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Impression_Native) ProtoMessage()    {}

func (m *BidRequest_Impression_Native) GetRequiredFields() uint64 {
	if m != nil && m.RequiredFields != nil {
		return *m.RequiredFields
	}
	return 0
}

func (m *BidRequest_Impression_Native) GetType() BidRequest_Impression_Native_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return BidRequest_Impression_Native_LINK
}

type BidRequest_Device struct {
	// 设备唯一标示
	// Android用IMEI md5sum，iOS用IDFA md5sum，其他用MAC地址
	Id         *string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	DeviceType *BidRequest_DeviceType      `protobuf:"varint,2,opt,name=device_type,enum=gdt.BidRequest_DeviceType" json:"device_type,omitempty"`
	Os         *BidRequest_OperatingSystem `protobuf:"varint,3,opt,name=os,enum=gdt.BidRequest_OperatingSystem" json:"os,omitempty"`
	OsVersion  *string                     `protobuf:"bytes,4,opt,name=os_version" json:"os_version,omitempty"`
	UserAgent  *string                     `protobuf:"bytes,5,opt,name=user_agent" json:"user_agent,omitempty"`
	// 屏幕宽度，单位:像素
	ScreenWidth *int32 `protobuf:"varint,6,opt,name=screen_width" json:"screen_width,omitempty"`
	// 屏幕高度，单位:像素
	ScreenHeight *int32 `protobuf:"varint,7,opt,name=screen_height" json:"screen_height,omitempty"`
	// 屏幕每英寸像素
	Dpi            *int32                     `protobuf:"varint,8,opt,name=dpi" json:"dpi,omitempty"`
	Carrier        *BidRequest_Carrier        `protobuf:"varint,9,opt,name=carrier,enum=gdt.BidRequest_Carrier" json:"carrier,omitempty"`
	ConnectionType *BidRequest_ConnectionType `protobuf:"varint,10,opt,name=connection_type,enum=gdt.BidRequest_ConnectionType" json:"connection_type,omitempty"`
	// 设备的品牌型号
	BrandAndModel *string `protobuf:"bytes,11,opt,name=brand_and_model" json:"brand_and_model,omitempty"`
	// 设备的语言，zh en等
	Language *string `protobuf:"bytes,12,opt,name=language" json:"language,omitempty"`
	// iOS设备的IDFA明文
	Idfa *string `protobuf:"bytes,13,opt,name=idfa" json:"idfa,omitempty"`
	// 设备生产厂家
	Manufacturer *string `protobuf:"bytes,14,opt,name=manufacturer" json:"manufacturer,omitempty"`
	// Android设备的Android ID，取md5sum摘要，摘要小写
	AndroidId        *string `protobuf:"bytes,15,opt,name=android_id" json:"android_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BidRequest_Device) Reset()         { *m = BidRequest_Device{} }
func (m *BidRequest_Device) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Device) ProtoMessage()    {}

func (m *BidRequest_Device) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *BidRequest_Device) GetDeviceType() BidRequest_DeviceType {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return BidRequest_DEVICETYPE_UNKNOWN
}

func (m *BidRequest_Device) GetOs() BidRequest_OperatingSystem {
	if m != nil && m.Os != nil {
		return *m.Os
	}
	return BidRequest_OS_UNKNOWN
}

func (m *BidRequest_Device) GetOsVersion() string {
	if m != nil && m.OsVersion != nil {
		return *m.OsVersion
	}
	return ""
}

func (m *BidRequest_Device) GetUserAgent() string {
	if m != nil && m.UserAgent != nil {
		return *m.UserAgent
	}
	return ""
}

func (m *BidRequest_Device) GetScreenWidth() int32 {
	if m != nil && m.ScreenWidth != nil {
		return *m.ScreenWidth
	}
	return 0
}

func (m *BidRequest_Device) GetScreenHeight() int32 {
	if m != nil && m.ScreenHeight != nil {
		return *m.ScreenHeight
	}
	return 0
}

func (m *BidRequest_Device) GetDpi() int32 {
	if m != nil && m.Dpi != nil {
		return *m.Dpi
	}
	return 0
}

func (m *BidRequest_Device) GetCarrier() BidRequest_Carrier {
	if m != nil && m.Carrier != nil {
		return *m.Carrier
	}
	return BidRequest_CARRIER_UNKNOWN
}

func (m *BidRequest_Device) GetConnectionType() BidRequest_ConnectionType {
	if m != nil && m.ConnectionType != nil {
		return *m.ConnectionType
	}
	return BidRequest_CONNECTIONTYPE_UNKNOWN
}

func (m *BidRequest_Device) GetBrandAndModel() string {
	if m != nil && m.BrandAndModel != nil {
		return *m.BrandAndModel
	}
	return ""
}

func (m *BidRequest_Device) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *BidRequest_Device) GetIdfa() string {
	if m != nil && m.Idfa != nil {
		return *m.Idfa
	}
	return ""
}

func (m *BidRequest_Device) GetManufacturer() string {
	if m != nil && m.Manufacturer != nil {
		return *m.Manufacturer
	}
	return ""
}

func (m *BidRequest_Device) GetAndroidId() string {
	if m != nil && m.AndroidId != nil {
		return *m.AndroidId
	}
	return ""
}

type BidRequest_User struct {
	Id               *string                      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserDemographic  *BidRequest_User_Demographic `protobuf:"bytes,2,opt,name=user_demographic" json:"user_demographic,omitempty"`
	Verticals        []*BidRequest_User_Vertical  `protobuf:"bytes,3,rep,name=verticals" json:"verticals,omitempty"`
	KeyWords         []*BidRequest_User_KeyWord   `protobuf:"bytes,8,rep,name=key_words" json:"key_words,omitempty"`
	AudienceIds      []uint32                     `protobuf:"varint,10,rep,name=audience_ids" json:"audience_ids,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *BidRequest_User) Reset()         { *m = BidRequest_User{} }
func (m *BidRequest_User) String() string { return proto.CompactTextString(m) }
func (*BidRequest_User) ProtoMessage()    {}

func (m *BidRequest_User) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *BidRequest_User) GetUserDemographic() *BidRequest_User_Demographic {
	if m != nil {
		return m.UserDemographic
	}
	return nil
}

func (m *BidRequest_User) GetVerticals() []*BidRequest_User_Vertical {
	if m != nil {
		return m.Verticals
	}
	return nil
}

func (m *BidRequest_User) GetKeyWords() []*BidRequest_User_KeyWord {
	if m != nil {
		return m.KeyWords
	}
	return nil
}

func (m *BidRequest_User) GetAudienceIds() []uint32 {
	if m != nil {
		return m.AudienceIds
	}
	return nil
}

type BidRequest_User_Demographic struct {
	Gender    *BidRequest_User_Demographic_Gender    `protobuf:"varint,1,opt,name=gender,enum=gdt.BidRequest_User_Demographic_Gender,def=0" json:"gender,omitempty"`
	Education *BidRequest_User_Demographic_Education `protobuf:"varint,2,opt,name=education,enum=gdt.BidRequest_User_Demographic_Education,def=0" json:"education,omitempty"`
	// 年龄区间，两端都是闭区间
	AgeLow       *int32                                               `protobuf:"varint,3,opt,name=age_low,def=0" json:"age_low,omitempty"`
	AgeHigh      *int32                                               `protobuf:"varint,4,opt,name=age_high,def=999" json:"age_high,omitempty"`
	ConsumeLevel *BidRequest_User_Demographic_ConsumptionAbilityLevel `protobuf:"varint,5,opt,name=consume_level,enum=gdt.BidRequest_User_Demographic_ConsumptionAbilityLevel" json:"consume_level,omitempty"`
	// 由LBS数据挖掘得到的用户住房价格数据
	HousePrice       *uint32                                      `protobuf:"varint,6,opt,name=house_price" json:"house_price,omitempty"`
	MarriageStatus   []BidRequest_User_Demographic_MarriageStatus `protobuf:"varint,8,rep,name=marriage_status,enum=gdt.BidRequest_User_Demographic_MarriageStatus" json:"marriage_status,omitempty"`
	XXX_unrecognized []byte                                       `json:"-"`
}

func (m *BidRequest_User_Demographic) Reset()         { *m = BidRequest_User_Demographic{} }
func (m *BidRequest_User_Demographic) String() string { return proto.CompactTextString(m) }
func (*BidRequest_User_Demographic) ProtoMessage()    {}

const Default_BidRequest_User_Demographic_Gender BidRequest_User_Demographic_Gender = BidRequest_User_Demographic_GENDER_UNKNOWN
const Default_BidRequest_User_Demographic_Education BidRequest_User_Demographic_Education = BidRequest_User_Demographic_EDUCATION_UNKNOWN
const Default_BidRequest_User_Demographic_AgeLow int32 = 0
const Default_BidRequest_User_Demographic_AgeHigh int32 = 999

func (m *BidRequest_User_Demographic) GetGender() BidRequest_User_Demographic_Gender {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return Default_BidRequest_User_Demographic_Gender
}

func (m *BidRequest_User_Demographic) GetEducation() BidRequest_User_Demographic_Education {
	if m != nil && m.Education != nil {
		return *m.Education
	}
	return Default_BidRequest_User_Demographic_Education
}

func (m *BidRequest_User_Demographic) GetAgeLow() int32 {
	if m != nil && m.AgeLow != nil {
		return *m.AgeLow
	}
	return Default_BidRequest_User_Demographic_AgeLow
}

func (m *BidRequest_User_Demographic) GetAgeHigh() int32 {
	if m != nil && m.AgeHigh != nil {
		return *m.AgeHigh
	}
	return Default_BidRequest_User_Demographic_AgeHigh
}

func (m *BidRequest_User_Demographic) GetConsumeLevel() BidRequest_User_Demographic_ConsumptionAbilityLevel {
	if m != nil && m.ConsumeLevel != nil {
		return *m.ConsumeLevel
	}
	return BidRequest_User_Demographic_CONSUMPTION_ABILITY_LEVEL_UNKNOWN
}

func (m *BidRequest_User_Demographic) GetHousePrice() uint32 {
	if m != nil && m.HousePrice != nil {
		return *m.HousePrice
	}
	return 0
}

func (m *BidRequest_User_Demographic) GetMarriageStatus() []BidRequest_User_Demographic_MarriageStatus {
	if m != nil {
		return m.MarriageStatus
	}
	return nil
}

type BidRequest_User_Vertical struct {
	// 用户兴趣 id
	Id *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// 用户兴趣权重，取值范围0.005~1
	Weight           *float32 `protobuf:"fixed32,2,opt,name=weight" json:"weight,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BidRequest_User_Vertical) Reset()         { *m = BidRequest_User_Vertical{} }
func (m *BidRequest_User_Vertical) String() string { return proto.CompactTextString(m) }
func (*BidRequest_User_Vertical) ProtoMessage()    {}

func (m *BidRequest_User_Vertical) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *BidRequest_User_Vertical) GetWeight() float32 {
	if m != nil && m.Weight != nil {
		return *m.Weight
	}
	return 0
}

// 关键词
type BidRequest_User_KeyWord struct {
	Id               *uint64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Weight           *float32 `protobuf:"fixed32,2,opt,name=weight" json:"weight,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BidRequest_User_KeyWord) Reset()         { *m = BidRequest_User_KeyWord{} }
func (m *BidRequest_User_KeyWord) String() string { return proto.CompactTextString(m) }
func (*BidRequest_User_KeyWord) ProtoMessage()    {}

func (m *BidRequest_User_KeyWord) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *BidRequest_User_KeyWord) GetWeight() float32 {
	if m != nil && m.Weight != nil {
		return *m.Weight
	}
	return 0
}

type BidRequest_Geo struct {
	// 纬度 * 1 000 000（火星坐标系）
	Latitude *int32 `protobuf:"varint,1,opt,name=latitude" json:"latitude,omitempty"`
	// 精度 * 1 000 000（火星坐标系）
	Longitude *int32 `protobuf:"varint,2,opt,name=longitude" json:"longitude,omitempty"`
	// 经纬度精度半径，单位米
	Accuracy         *float64 `protobuf:"fixed64,3,opt,name=accuracy" json:"accuracy,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BidRequest_Geo) Reset()         { *m = BidRequest_Geo{} }
func (m *BidRequest_Geo) String() string { return proto.CompactTextString(m) }
func (*BidRequest_Geo) ProtoMessage()    {}

func (m *BidRequest_Geo) GetLatitude() int32 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *BidRequest_Geo) GetLongitude() int32 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

func (m *BidRequest_Geo) GetAccuracy() float64 {
	if m != nil && m.Accuracy != nil {
		return *m.Accuracy
	}
	return 0
}

type BidRequest_App struct {
	// App所属行业id。
	// 取值见《APP行业分类.xlsx》
	IndustryId *int64 `protobuf:"varint,1,opt,name=industry_id" json:"industry_id,omitempty"`
	// App唯一标识，Andorid应用对应其packegname，iOS应用对应其bundle id
	AppBundleId      *string `protobuf:"bytes,2,opt,name=app_bundle_id" json:"app_bundle_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BidRequest_App) Reset()         { *m = BidRequest_App{} }
func (m *BidRequest_App) String() string { return proto.CompactTextString(m) }
func (*BidRequest_App) ProtoMessage()    {}

func (m *BidRequest_App) GetIndustryId() int64 {
	if m != nil && m.IndustryId != nil {
		return *m.IndustryId
	}
	return 0
}

func (m *BidRequest_App) GetAppBundleId() string {
	if m != nil && m.AppBundleId != nil {
		return *m.AppBundleId
	}
	return ""
}

type BidResponse struct {
	// 来自BidRequest.id
	// 替换曝光、点击地址中的宏%%BID_REQUEST_ID%%
	RequestId *string                `protobuf:"bytes,1,opt,name=request_id" json:"request_id,omitempty"`
	SeatBids  []*BidResponse_SeatBid `protobuf:"bytes,2,rep,name=seat_bids" json:"seat_bids,omitempty"`
	// 收到BidRequest至发送完BidResponse的用时，单位:毫秒
	ProcessingTimeMs *int32                    `protobuf:"varint,3,opt,name=processing_time_ms" json:"processing_time_ms,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *BidResponse) Reset()         { *m = BidResponse{} }
func (m *BidResponse) String() string { return proto.CompactTextString(m) }
func (*BidResponse) ProtoMessage()    {}

var extRange_BidResponse = []proto.ExtensionRange{
	{10000, 536870911},
}

func (*BidResponse) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_BidResponse
}
func (m *BidResponse) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

func (m *BidResponse) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *BidResponse) GetSeatBids() []*BidResponse_SeatBid {
	if m != nil {
		return m.SeatBids
	}
	return nil
}

func (m *BidResponse) GetProcessingTimeMs() int32 {
	if m != nil && m.ProcessingTimeMs != nil {
		return *m.ProcessingTimeMs
	}
	return 0
}

type BidResponse_Bid struct {
	// DSP提供的素材id
	CreativeId *string `protobuf:"bytes,1,opt,name=creative_id" json:"creative_id,omitempty"`
	// DSP最高出价，CPM，单位:分
	BidPrice *int32 `protobuf:"varint,2,opt,name=bid_price" json:"bid_price,omitempty"`
	// 替换DSP曝光监测URL里的宏%%IMPRESSION_PARAM%%，最长500字节，超长截断
	// 随素材一起上传的DSP曝光监测URL形如：
	//  http://imp.dsp1.com?bid_request_id=%%BID_REQUEST_ID%%&
	//  impression_param=%%IMPRESSION_PARAM%%&win_price=%%WIN_PRICE%%
	// 通过宏%%IMPRESSION_PARAM%%，DSP可以把内部参数从竞价模块透明传输到
	// 曝光监测模块。
	// DSP负责参数加解密
	ImpressionParam *string `protobuf:"bytes,3,opt,name=impression_param" json:"impression_param,omitempty"`
	// 替换DSP点击监测URL里的宏%%CLICK_PARAM%%，最长500字节，超长截断
	// 随素材一起上传的DSP点击监测URL形如：
	//  http://click.dsp1.com?bid_request_id=%%BID_REQUEST_ID%%&
	//  click_param=%%CLICK_PARAM%%
	// 通过宏%%CLICK_PARAM%%，DSP可以把内部参数从竞价模块透明传输到
	// 点击监测模块。
	// DSP负责参数加解密
	ClickParam      *string                          `protobuf:"bytes,4,opt,name=click_param" json:"click_param,omitempty"`
	DynamicCreative *BidResponse_Bid_DynamicCreative `protobuf:"bytes,5,opt,name=dynamic_creative" json:"dynamic_creative,omitempty"`
	// 是否让adx过滤已安装app
	AppFilter *bool `protobuf:"varint,6,opt,name=app_filter,def=0" json:"app_filter,omitempty"`
	// DSP返回的deal id
	DealId           *string                   `protobuf:"bytes,7,opt,name=deal_id" json:"deal_id,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *BidResponse_Bid) Reset()         { *m = BidResponse_Bid{} }
func (m *BidResponse_Bid) String() string { return proto.CompactTextString(m) }
func (*BidResponse_Bid) ProtoMessage()    {}

var extRange_BidResponse_Bid = []proto.ExtensionRange{
	{10000, 536870911},
}

func (*BidResponse_Bid) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_BidResponse_Bid
}
func (m *BidResponse_Bid) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

const Default_BidResponse_Bid_AppFilter bool = false

func (m *BidResponse_Bid) GetCreativeId() string {
	if m != nil && m.CreativeId != nil {
		return *m.CreativeId
	}
	return ""
}

func (m *BidResponse_Bid) GetBidPrice() int32 {
	if m != nil && m.BidPrice != nil {
		return *m.BidPrice
	}
	return 0
}

func (m *BidResponse_Bid) GetImpressionParam() string {
	if m != nil && m.ImpressionParam != nil {
		return *m.ImpressionParam
	}
	return ""
}

func (m *BidResponse_Bid) GetClickParam() string {
	if m != nil && m.ClickParam != nil {
		return *m.ClickParam
	}
	return ""
}

func (m *BidResponse_Bid) GetDynamicCreative() *BidResponse_Bid_DynamicCreative {
	if m != nil {
		return m.DynamicCreative
	}
	return nil
}

func (m *BidResponse_Bid) GetAppFilter() bool {
	if m != nil && m.AppFilter != nil {
		return *m.AppFilter
	}
	return Default_BidResponse_Bid_AppFilter
}

func (m *BidResponse_Bid) GetDealId() string {
	if m != nil && m.DealId != nil {
		return *m.DealId
	}
	return ""
}

type BidResponse_Bid_DynamicCreative struct {
	// DSP动态创意代码片段
	HtmlSnippet *string `protobuf:"bytes,1,opt,name=html_snippet" json:"html_snippet,omitempty"`
	// DSP动态创意代码片段是否内嵌广点通提供的JS辅助代码。
	// 当DSP以IFrame代码片段的形式来提供动态创意的时候，
	// 可以通过调用该JS代码提供的接口来完成以下功能:
	// 1. 通知流量方IFrame内广告相关素材加载完成，可以展示。
	// 2. 通知流量方发生了用户点击,流量方负责使用浏览器打开跳转地址
	// 具体JS接口见《腾讯广点通广告交易平台接入说明文档》
	SupportGdtHelperJs *bool `protobuf:"varint,2,opt,name=support_gdt_helper_js" json:"support_gdt_helper_js,omitempty"`
	// DSP动态创意对应的商品信息
	ProductInfos []*BidResponse_Bid_DynamicCreative_ProductInfo `protobuf:"bytes,3,rep,name=product_infos" json:"product_infos,omitempty"`
	// DSP动态创意对应的点击跳转域名白名单,
	// 当动态创意使用iframe方式不嵌入广点通js或者使用非iframe代码片段的时候，
	// 需要返回点击跳转地址的完整域名。
	// 域名白名单只需要覆盖初始打开URL的完整域名,
	// 在浏览器打开URL后，后续的redirect不受限制
	ClickUrlDomainWhitelist []string `protobuf:"bytes,4,rep,name=click_url_domain_whitelist" json:"click_url_domain_whitelist,omitempty"`
	XXX_unrecognized        []byte   `json:"-"`
}

func (m *BidResponse_Bid_DynamicCreative) Reset()         { *m = BidResponse_Bid_DynamicCreative{} }
func (m *BidResponse_Bid_DynamicCreative) String() string { return proto.CompactTextString(m) }
func (*BidResponse_Bid_DynamicCreative) ProtoMessage()    {}

func (m *BidResponse_Bid_DynamicCreative) GetHtmlSnippet() string {
	if m != nil && m.HtmlSnippet != nil {
		return *m.HtmlSnippet
	}
	return ""
}

func (m *BidResponse_Bid_DynamicCreative) GetSupportGdtHelperJs() bool {
	if m != nil && m.SupportGdtHelperJs != nil {
		return *m.SupportGdtHelperJs
	}
	return false
}

func (m *BidResponse_Bid_DynamicCreative) GetProductInfos() []*BidResponse_Bid_DynamicCreative_ProductInfo {
	if m != nil {
		return m.ProductInfos
	}
	return nil
}

func (m *BidResponse_Bid_DynamicCreative) GetClickUrlDomainWhitelist() []string {
	if m != nil {
		return m.ClickUrlDomainWhitelist
	}
	return nil
}

type BidResponse_Bid_DynamicCreative_ProductInfo struct {
	ProductId *string `protobuf:"bytes,1,opt,name=product_id" json:"product_id,omitempty"`
	// 商品一级行业
	// 取值见《广告主行业分类.xlsx》
	ProductIndustry *int64 `protobuf:"varint,2,opt,name=product_industry" json:"product_industry,omitempty"`
	// 商品二级行业
	// 取值见《广告主行业分类.xlsx》
	ProductCategory *int64 `protobuf:"varint,3,opt,name=product_category" json:"product_category,omitempty"`
	// 商品名称
	ProductName *string `protobuf:"bytes,4,opt,name=product_name" json:"product_name,omitempty"`
	// 商品描述
	ProductDescription *string `protobuf:"bytes,5,opt,name=product_description" json:"product_description,omitempty"`
	// 商品图片地址
	ProductMultimediaUrl *string `protobuf:"bytes,6,opt,name=product_multimedia_url" json:"product_multimedia_url,omitempty"`
	XXX_unrecognized     []byte  `json:"-"`
}

func (m *BidResponse_Bid_DynamicCreative_ProductInfo) Reset() {
	*m = BidResponse_Bid_DynamicCreative_ProductInfo{}
}
func (m *BidResponse_Bid_DynamicCreative_ProductInfo) String() string {
	return proto.CompactTextString(m)
}
func (*BidResponse_Bid_DynamicCreative_ProductInfo) ProtoMessage() {}

func (m *BidResponse_Bid_DynamicCreative_ProductInfo) GetProductId() string {
	if m != nil && m.ProductId != nil {
		return *m.ProductId
	}
	return ""
}

func (m *BidResponse_Bid_DynamicCreative_ProductInfo) GetProductIndustry() int64 {
	if m != nil && m.ProductIndustry != nil {
		return *m.ProductIndustry
	}
	return 0
}

func (m *BidResponse_Bid_DynamicCreative_ProductInfo) GetProductCategory() int64 {
	if m != nil && m.ProductCategory != nil {
		return *m.ProductCategory
	}
	return 0
}

func (m *BidResponse_Bid_DynamicCreative_ProductInfo) GetProductName() string {
	if m != nil && m.ProductName != nil {
		return *m.ProductName
	}
	return ""
}

func (m *BidResponse_Bid_DynamicCreative_ProductInfo) GetProductDescription() string {
	if m != nil && m.ProductDescription != nil {
		return *m.ProductDescription
	}
	return ""
}

func (m *BidResponse_Bid_DynamicCreative_ProductInfo) GetProductMultimediaUrl() string {
	if m != nil && m.ProductMultimediaUrl != nil {
		return *m.ProductMultimediaUrl
	}
	return ""
}

type BidResponse_SeatBid struct {
	// 来自BidRequest.impressions.id
	ImpressionId     *string            `protobuf:"bytes,1,opt,name=impression_id" json:"impression_id,omitempty"`
	Bids             []*BidResponse_Bid `protobuf:"bytes,2,rep,name=bids" json:"bids,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *BidResponse_SeatBid) Reset()         { *m = BidResponse_SeatBid{} }
func (m *BidResponse_SeatBid) String() string { return proto.CompactTextString(m) }
func (*BidResponse_SeatBid) ProtoMessage()    {}

func (m *BidResponse_SeatBid) GetImpressionId() string {
	if m != nil && m.ImpressionId != nil {
		return *m.ImpressionId
	}
	return ""
}

func (m *BidResponse_SeatBid) GetBids() []*BidResponse_Bid {
	if m != nil {
		return m.Bids
	}
	return nil
}

func init() {
	proto.RegisterType((*BidRequest)(nil), "gdt.BidRequest")
	proto.RegisterType((*BidRequest_Impression)(nil), "gdt.BidRequest.Impression")
	proto.RegisterType((*BidRequest_Impression_Native)(nil), "gdt.BidRequest.Impression.Native")
	proto.RegisterType((*BidRequest_Device)(nil), "gdt.BidRequest.Device")
	proto.RegisterType((*BidRequest_User)(nil), "gdt.BidRequest.User")
	proto.RegisterType((*BidRequest_User_Demographic)(nil), "gdt.BidRequest.User.Demographic")
	proto.RegisterType((*BidRequest_User_Vertical)(nil), "gdt.BidRequest.User.Vertical")
	proto.RegisterType((*BidRequest_User_KeyWord)(nil), "gdt.BidRequest.User.KeyWord")
	proto.RegisterType((*BidRequest_Geo)(nil), "gdt.BidRequest.Geo")
	proto.RegisterType((*BidRequest_App)(nil), "gdt.BidRequest.App")
	proto.RegisterType((*BidResponse)(nil), "gdt.BidResponse")
	proto.RegisterType((*BidResponse_Bid)(nil), "gdt.BidResponse.Bid")
	proto.RegisterType((*BidResponse_Bid_DynamicCreative)(nil), "gdt.BidResponse.Bid.DynamicCreative")
	proto.RegisterType((*BidResponse_Bid_DynamicCreative_ProductInfo)(nil), "gdt.BidResponse.Bid.DynamicCreative.ProductInfo")
	proto.RegisterType((*BidResponse_SeatBid)(nil), "gdt.BidResponse.SeatBid")
	proto.RegisterEnum("gdt.BidRequest_DeviceType", BidRequest_DeviceType_name, BidRequest_DeviceType_value)
	proto.RegisterEnum("gdt.BidRequest_Carrier", BidRequest_Carrier_name, BidRequest_Carrier_value)
	proto.RegisterEnum("gdt.BidRequest_ConnectionType", BidRequest_ConnectionType_name, BidRequest_ConnectionType_value)
	proto.RegisterEnum("gdt.BidRequest_OperatingSystem", BidRequest_OperatingSystem_name, BidRequest_OperatingSystem_value)
	proto.RegisterEnum("gdt.BidRequest_Impression_Native_Fields", BidRequest_Impression_Native_Fields_name, BidRequest_Impression_Native_Fields_value)
	proto.RegisterEnum("gdt.BidRequest_Impression_Native_Type", BidRequest_Impression_Native_Type_name, BidRequest_Impression_Native_Type_value)
	proto.RegisterEnum("gdt.BidRequest_User_Demographic_Gender", BidRequest_User_Demographic_Gender_name, BidRequest_User_Demographic_Gender_value)
	proto.RegisterEnum("gdt.BidRequest_User_Demographic_Education", BidRequest_User_Demographic_Education_name, BidRequest_User_Demographic_Education_value)
	proto.RegisterEnum("gdt.BidRequest_User_Demographic_ConsumptionAbilityLevel", BidRequest_User_Demographic_ConsumptionAbilityLevel_name, BidRequest_User_Demographic_ConsumptionAbilityLevel_value)
	proto.RegisterEnum("gdt.BidRequest_User_Demographic_MarriageStatus", BidRequest_User_Demographic_MarriageStatus_name, BidRequest_User_Demographic_MarriageStatus_value)
}
