// Code generated by protoc-gen-go.
// source: zplay_extensions.proto
// DO NOT EDIT!

/*
Package zplay is a generated protocol buffer package.

It is generated from these files:
	zplay_extensions.proto
	zplay.proto

It has these top-level messages:
	BidRequest
	BidResponse
	NativeRequest
	NativeResponse
*/
package zplay

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var E_Version = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest)(nil),
	ExtensionType: (*int32)(nil),
	Field:         200,
	Name:          "zplay.version",
	Tag:           "varint,200,opt,name=version",
}

var E_IsPing = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest)(nil),
	ExtensionType: (*bool)(nil),
	Field:         202,
	Name:          "zplay.is_ping",
	Tag:           "varint,202,opt,name=is_ping",
}

var E_NeedHttps = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest)(nil),
	ExtensionType: (*bool)(nil),
	Field:         203,
	Name:          "zplay.need_https",
	Tag:           "varint,203,opt,name=need_https",
}

var E_Accu = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest_Geo)(nil),
	ExtensionType: (*int32)(nil),
	Field:         200,
	Name:          "zplay.accu",
	Tag:           "varint,200,opt,name=accu",
}

var E_Street = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest_Geo)(nil),
	ExtensionType: (*string)(nil),
	Field:         201,
	Name:          "zplay.street",
	Tag:           "bytes,201,opt,name=street",
}

var E_IsSplashScreen = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest_Imp)(nil),
	ExtensionType: (*bool)(nil),
	Field:         200,
	Name:          "zplay.is_splash_screen",
	Tag:           "varint,200,opt,name=is_splash_screen",
}

var E_InventoryTypes = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest_Imp)(nil),
	ExtensionType: ([]int32)(nil),
	Field:         201,
	Name:          "zplay.inventory_types",
	Tag:           "varint,201,rep,name=inventory_types",
}

var E_Plmn = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest_Device)(nil),
	ExtensionType: (*string)(nil),
	Field:         200,
	Name:          "zplay.plmn",
	Tag:           "bytes,200,opt,name=plmn",
}

var E_Imei = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest_Device)(nil),
	ExtensionType: (*string)(nil),
	Field:         201,
	Name:          "zplay.imei",
	Tag:           "bytes,201,opt,name=imei",
}

var E_Mac = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest_Device)(nil),
	ExtensionType: (*string)(nil),
	Field:         202,
	Name:          "zplay.mac",
	Tag:           "bytes,202,opt,name=mac",
}

var E_AndroidId = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest_Device)(nil),
	ExtensionType: (*string)(nil),
	Field:         203,
	Name:          "zplay.android_id",
	Tag:           "bytes,203,opt,name=android_id",
}

var E_Adid = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest_Device)(nil),
	ExtensionType: (*string)(nil),
	Field:         204,
	Name:          "zplay.adid",
	Tag:           "bytes,204,opt,name=adid",
}

var E_Orientation = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest_Device)(nil),
	ExtensionType: (*int32)(nil),
	Field:         205,
	Name:          "zplay.orientation",
	Tag:           "varint,205,opt,name=orientation",
}

var E_Imsi = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest_Device)(nil),
	ExtensionType: (*string)(nil),
	Field:         206,
	Name:          "zplay.imsi",
	Tag:           "bytes,206,opt,name=imsi",
}

var E_Imptrackers = &proto.ExtensionDesc{
	ExtendedType:  (*BidResponse_SeatBid_Bid)(nil),
	ExtensionType: ([]string)(nil),
	Field:         200,
	Name:          "zplay.imptrackers",
	Tag:           "bytes,200,rep,name=imptrackers",
}

var E_Clktrackers = &proto.ExtensionDesc{
	ExtendedType:  (*BidResponse_SeatBid_Bid)(nil),
	ExtensionType: ([]string)(nil),
	Field:         201,
	Name:          "zplay.clktrackers",
	Tag:           "bytes,201,rep,name=clktrackers",
}

var E_Clkurl = &proto.ExtensionDesc{
	ExtendedType:  (*BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*string)(nil),
	Field:         202,
	Name:          "zplay.clkurl",
	Tag:           "bytes,202,opt,name=clkurl",
}

var E_HtmlSnippet = &proto.ExtensionDesc{
	ExtendedType:  (*BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*string)(nil),
	Field:         203,
	Name:          "zplay.html_snippet",
	Tag:           "bytes,203,opt,name=html_snippet",
}

var E_AppVer = &proto.ExtensionDesc{
	ExtendedType:  (*BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*string)(nil),
	Field:         204,
	Name:          "zplay.app_ver",
	Tag:           "bytes,204,opt,name=app_ver",
}

var E_InventoryType = &proto.ExtensionDesc{
	ExtendedType:  (*BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*int32)(nil),
	Field:         205,
	Name:          "zplay.inventory_type",
	Tag:           "varint,205,opt,name=inventory_type",
}

var E_Title = &proto.ExtensionDesc{
	ExtendedType:  (*BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*string)(nil),
	Field:         206,
	Name:          "zplay.title",
	Tag:           "bytes,206,opt,name=title",
}

var E_Desc = &proto.ExtensionDesc{
	ExtendedType:  (*BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*string)(nil),
	Field:         207,
	Name:          "zplay.desc",
	Tag:           "bytes,207,opt,name=desc",
}

var E_Action = &proto.ExtensionDesc{
	ExtendedType:  (*BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*int32)(nil),
	Field:         208,
	Name:          "zplay.action",
	Tag:           "varint,208,opt,name=action",
}

var E_DownloadFileName = &proto.ExtensionDesc{
	ExtendedType:  (*BidResponse_SeatBid_Bid)(nil),
	ExtensionType: (*string)(nil),
	Field:         209,
	Name:          "zplay.download_file_name",
	Tag:           "bytes,209,opt,name=download_file_name",
}

var E_LinkType = &proto.ExtensionDesc{
	ExtendedType:  (*NativeResponse_Link)(nil),
	ExtensionType: (*int32)(nil),
	Field:         200,
	Name:          "zplay.link_type",
	Tag:           "varint,200,opt,name=link_type",
}

func init() {
	proto.RegisterExtension(E_Version)
	proto.RegisterExtension(E_IsPing)
	proto.RegisterExtension(E_NeedHttps)
	proto.RegisterExtension(E_Accu)
	proto.RegisterExtension(E_Street)
	proto.RegisterExtension(E_IsSplashScreen)
	proto.RegisterExtension(E_InventoryTypes)
	proto.RegisterExtension(E_Plmn)
	proto.RegisterExtension(E_Imei)
	proto.RegisterExtension(E_Mac)
	proto.RegisterExtension(E_AndroidId)
	proto.RegisterExtension(E_Adid)
	proto.RegisterExtension(E_Orientation)
	proto.RegisterExtension(E_Imsi)
	proto.RegisterExtension(E_Imptrackers)
	proto.RegisterExtension(E_Clktrackers)
	proto.RegisterExtension(E_Clkurl)
	proto.RegisterExtension(E_HtmlSnippet)
	proto.RegisterExtension(E_AppVer)
	proto.RegisterExtension(E_InventoryType)
	proto.RegisterExtension(E_Title)
	proto.RegisterExtension(E_Desc)
	proto.RegisterExtension(E_Action)
	proto.RegisterExtension(E_DownloadFileName)
	proto.RegisterExtension(E_LinkType)
}
